### ISSUE TITLE
Add CUDA includes to the PUBLIC include directories

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#104]
https://github.com/eyalroz/cuda-api-wrappers/blob/master/CMakeLists.txt#L73

Does not seem to add the include directory to the `PUBLIC` include directories of the targets. Therefore this should be added to:

https://github.com/eyalroz/cuda-api-wrappers/blob/master/CMakeLists.txt#L97

Suggestion:

```cmake
target_include_directories(
	${PROJECT_NAME}
		PUBLIC
		"$<INSTALL_INTERFACE:include>"
		"$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>"
                "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}"
)
```

Otherwise CPP projects, which use `cuda-api-wrappers` won't be able to find the CUDA include directories automatically.

**Comment by eyalroz** [comment]
I guess I was assuming if something uses the API wrappers they also have to use the CUDA includes, but ok, let's forego this assumption and add that.
