### ISSUE TITLE
cannot find -lcudadevrt  -lcudart_static

### ISSUE THREAD

**Issue by zingdle** [eyalroz/cuda-api-wrappers#106]
```
$ mkdir build && cd build

$ cmake ..

$ make
...
[ 13%] Linking CXX executable examples/bin/unified_addressing
/usr/bin/x86_64-linux-gnu-ld: cannot find -lcudadevrt
/usr/bin/x86_64-linux-gnu-ld: cannot find -lcudart_static
collect2: error: ld returned 1 exit status
CMakeFiles/unified_addressing.dir/build.make:84: recipe for target 'examples/bin/unified_addressing' failed

$ ls ~/.local/cuda-9.0/lib64 | grep cuda
libcudadevrt.a
libcudart.so
libcudart.so.9.0
libcudart.so.9.0.176
libcudart_static.a
```

I'm using CUDA 9.0 and g++ 6.5.0. Looks like it cannot find my customized CUDA lib folder. Any solutions for this?

Also, some similar warnings are given when compiling:
```
[ 11%] Building CXX object CMakeFiles/unified_addressing.dir/examples/by_runtime_api_module/unified_addressing.cpp.o                                  
In file included from /home/user/cuda-api-wrappers/src/cuda/api/device.hpp:13:0,                                                                       
                 from /home/user/cuda-api-wrappers/examples/by_runtime_api_module/unified_addressing.cpp:15:                                           
/home/user/cuda-api-wrappers/src/cuda/api/device_properties.hpp:99:13: warning: In the GNU C Library, "major" is defined                               
 by <sys/sysmacros.h>. For historical compatibility, it is                                                                                            
 currently defined by <sys/types.h> as well, but we plan to                                                                                           
 remove this soon. To use "major", include <sys/sysmacros.h>                                                                                          
 directly. If you did not intend to use a system-defined macro                                                                                        
 "major", you should undefine it after including <sys/types.h>.                                                                                       
  unsigned as_combined_number() const noexcept { return major() * 10 + minor_; }                                                                      
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                              
```

**Comment by eyalroz** [comment]
About the _second_ problem: The API wrapper headers don't include `sys/types.h` - so it's your code that does that. Well, you should follow the advice, and have:
```
#undefine major
```
after including `<sys/types.h>`.

**Comment by eyalroz** [comment]
About the _first_ problem: You need to allow CMake to find your CUDA installation. See:

[How to let cmake find CUDA](https://stackoverflow.com/q/19980412/1593077)

and follow the recommendation by invoking CMake with the appropriate variable defined:
```
$ cmake -D CUDA_TOOLKIT_ROOT_DIR=$HOME/.local/cuda-9.0/ .
```

**Comment by zingdle** [comment]
Well actually I'm using the newly cloned repo to `make example`. I changed nothing to the project and there are those warnings.

I tried to set `CUDA_TOOLKIT_ROOT_DIR` but the cmake warns:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CUDA_TOOLKIT_ROOT_DIR
``` 
and tried to set environment variable `CUDA_BIN_PATH`. Both are faild to make it linked.

**Comment by eyalroz** [comment]
@zingdle : But the unified_addressing example, from which you get the error, doesn't include `<sys/types.h>` - so it's not supposed to get this warning. I can't quite figure out why that happens on your system. Perhaps you should add the macro un-definition after the standard library includes.

About the CMake issue: Try this instead:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/cuda/lib64
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/.local/cuda/include
```

**Comment by zingdle** [comment]
I switched my CUDA/g++ to default version(`/usr/local/cuda` and `/usr/local/bin/g++`) but these 2 problems are still unchanged.

Setting `LD_LIBRARY_PATH` and `CPLUS_INCLUDE_PATH` doesn't work for me. I'm curious why I need to set `CPLUS_INCLUDE_PATH`. 

Changing `LIBRARY_PATH`  did work for me but I don't think it's an elegant/proper way to do so:
```
export LIBRARY_PATH=$HOME/.local/cuda-9.0/lib64
```

**Comment by eyalroz** [comment]
I'm sorry, I don't know why this is happening to you... If more people experience it maybe I can understand if there's a problem with the package or someplace else.

**Comment by zingdle** [comment]
An easy way to reproduce: use [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) (nvidia/cuda:10.0-devel-ubuntu18.04)

It behaves exactly the same.

**Comment by codecircuit** [comment]
I can take a look at this. @zingdle Can you give exact steps how to reproduce your issue within the Docker container?

**Comment by zingdle** [comment]
Clone the repo in current directory then:
```
$ docker run -ti --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 -v $PWD/cuda-api-wrappers:/cuda-api-wrappers nvidia/cuda:10.0-devel-ubuntu18.04
# apt update
# apt install cmake
# cd /cuda-api-wrappers
# cmake .
# make examples
```
That should reproduce the problems.

**Comment by codecircuit** [comment]
This actually is an issue. The problem is that CMake does not register `cuda-api-wrappers` as a target, which uses CUDA at all. This issues occures for all `CXX` executables, which link against `cuda-api-wrappers`. A consistent solution would look like:

```cmake
find_package(cuda_runtime REQUIRED)
...
target_link_libraries(cuda-api-wrappers cuda_runtime::cuda_runtime)
...
```

This would require to write a CMake-Find-Module for the CUDA runtime libraries. This is also related to what I mentioned in:

https://github.com/eyalroz/cuda-api-wrappers/pull/102#discussion_r267714918

To my mind CMake should provide a way to distinguish the CUDA language and the CUDA libraries. But that can take a while, thus I can write a find module first.

I did not detect this issue, because I use custom CUDA installations and always set `LIBRARY_PATH` appropriately.

**Comment by eyalroz** [comment]
@codecircuit 
So, is the `find_package()` you suggested intended for a project which _uses_ cuda-api-wrappers or are you suggesting that it be used in cuda-api-wrappers' `CMakeLists.txt`?

Also - indeed, `cuda-api-wrappers` does not use the CUDA libraries for its compilation; it's more of an INTERFACE requirement, I'd say. I'm reminded of @DeveloperPaul123 's PR #80 , in which he added the CUDA libraries as an explicit dependency on WIN32. I suppose your suggestion is a sort of a generalization of that.

**Comment by DeveloperPaul123** [comment]
Yes this is basically the same problem I ran into. Even though `FindCUDA` is deprecated, it's still required if you want to link to the CUDA libraries from a non CUDA (i.e. `*.cu`) file.

**Comment by eyalroz** [comment]
@zingdle :
Could have have a look at [the branch](https://github.com/eyalroz/cuda-api-wrappers/tree/use-find-cuda) I've created, or PR #108  ? See if that helps?
@DeveloperPaul123: Could you also have a look, to check whether there's a regression after having removed the `if (WIN32)` section?

**Comment by zingdle** [comment]
It has no effect:
```
/usr/bin/c++   -Wall -Wextra -Wpedantic -Wno-missing-field-initializers -O3 -DNDEBUG   CMakeFiles/unified_addressing.dir/examples/by_runtime_api_module/unified_addressing.cpp.o  -o examples/bin/unified_addressing -lcudadevrt -lcudart_static -lrt -lpthread -ldl -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc lib/libcuda-api-wrappers.a -lc /usr/local/cuda/lib64/libcudart_static.a -lpthread -ldl /usr/lib/x86_64-linux-gnu/librt.so
/usr/bin/ld: cannot find -lcudadevrt
/usr/bin/ld: cannot find -lcudart_static
```

[Here](https://shawnliu.me/post/cuda-as-a-language-in-cmake/) the author suggests using `CMAKE_CUDA_IMPLICIT_LINK_DIRECTORIES`. I don't know if it could help.

Another thing that puzzled me is that on WIN32, `cudadevrt.lib;cudart.lib` is enough while on my machine according to the error, why are `-lcudart_static` and `-lcudadevrt` required?

**Comment by eyalroz** [comment]
>...  `CMAKE_CUDA_IMPLICIT_LINK_DIRECTORIES`. I don't know if it could help.

Well, please try it, and say if it helped. I'm only guessing since I'm not seeing it on my system. And docker somehow has problems with the fact that I don't use systemd, so I can't try that myself either.

**Comment by zingdle** [comment]
A quick-and-dirty solution for this issue is adding:
```
link_directories(${CMAKE_CUDA_IMPLICIT_LINK_DIRECTORIES})
```

But as @codecircuit pointed out, for every `CXX` that link against `cuda-api-wrappers`, it should link against cuda runtime library. I guess it's like the `rpath` in `cuda-api-wrappers` ? I have little experience in dealing with such secondary dependency problem...

**Comment by codecircuit** [comment]
I refer to current HEAD of branch `use-find-cuda` (52260ae28ee6b3818cbbcb938d816b0b762e48f6).
To resolve the build issues with the examples we need to remove the dynamic link from the examples:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9c16f49..9d60881 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -112,7 +112,7 @@ target_link_libraries(${PROJECT_NAME} ${CUDA_LIBRARIES})
 # Examples / Tests
 # -----------------------
 
-link_libraries(${CMAKE_CUDA_IMPLICIT_LINK_LIBRARIES} cuda-api-wrappers)
+link_libraries(cuda-api-wrappers)
 
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "examples/bin")
 add_executable(vectorAdd EXCLUDE_FROM_ALL examples/modified_cuda_samples/vectorAdd/vectorAdd.cu)
```

@eyalroz So up to now I think we are fine and do not need a find module for the CUDA runtime libraries, right? At least as long as `findCUDA` is supported.

**Comment by eyalroz** [comment]
@zingdle:
I've followed  @codecircuit 's suggestion and replaced the head of the `use-find-cuda` branch. Please check it out and see whether that lets the example programs build on docker and your system. You can also inspect the changes as PR #108  (it was updated with my recent forced-push).

**Comment by zingdle** [comment]
Thanks! Now it worked.
