### ISSUE TITLE
Compiling with --expt-relaxed-constexpr -G fails

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#112]
Example:

```cpp
#include <cuda/api_wrappers.hpp>

__global__ void kernel()
{
	extern __shared__ float foobar[];
	float* barbaz = foobar;
}

int main()
{
	auto device = cuda::device::current::get();
	auto stream = cuda::stream::create(device.id(), true);
}
```

This fails to compile for me with Visual Studio 2017, CUDA 10.1, but only with
flags: `--expt-relaxed-constexpr -G -Xcompiler " \MDd "`, which is a flag to choose the
host runtime library. `\MDd` is the multi threaded runtime library in debug mode, which is automatically chosen by Visual Studio in case of the Debug build. Maybe this it is not worth the time to investigate this further.

**Comment by eyalroz** [comment]
What's the error message you're getting?

Also, does this only happen with CUDA 10.1?

**Comment by codecircuit** [comment]
- Error message: `Alignment of argument does not match formal parameter '_'`
- I only checked with CUDA 10.1

I could remove the `stream` and still having the same error with this code:

```cpp
#include <cuda/api/device.hpp>



__global__ void kernel()
{
	extern __shared__ float foobar[];
	float* barbaz = foobar;
}

int main()
{
	cuda::device::current::scoped_override_t<> set_device_for_this_scope(0); // does not compile; should be `false` per default
	cuda::device::current::scoped_override_t<false> set_device_for_this_scope(0); // does not compile
	cuda::device::current::scoped_override_t<true> set_device_for_this_scope(0); // does compile

}
```

**Comment by eyalroz** [comment]
Well, this compiles for me with CUDA 9.2.

**Comment by eyalroz** [comment]
Do you still see this? If you can, can you copy the full error message (includes line numbers)?

**Comment by eyalroz** [comment]
Please reopen if you still get this.
