### ISSUE TITLE
Check kernel launch properties

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#114]
It might be useful to check the kernel launch properties at runtime. Thus if the kernel cannot be launched an error is thrown. To my mind this is also an expected behaviour of the cuda-api-wrappers, since all other functions of this library throw an error if something goes wrong. At this moment it can happen that the user launches a kernel with `cuda::launch` but nothing gets launched and no error is thrown e.g. if the kernel requires too many registers or too much static shared memory. This can easily be detected by e.g.:

```
kernel<<<1,1024>>>(...);
cuda::throw_if_error(cudaGetLastError());
```

Moreover this kind of error is **not** considered at a subsequent `cudaDeviceSynchronize()`, which makes it annoying to deal with.

I think it would be reasonable to integrate this into the kernel launch function of the wrappers.

**Comment by eyalroz** [comment]
Have you implemented this and want to post a PR?

**Comment by eyalroz** [comment]
Something like this maybe?:
```
diff --git a/src/cuda/api/kernel_launch.cuh b/src/cuda/api/kernel_launch.cuh
index 62dc1b9..fc671e8 100644
--- a/src/cuda/api/kernel_launch.cuh
+++ b/src/cuda/api/kernel_launch.cuh
@@ -131,6 +131,7 @@ inline void enqueue_launch(
                        launch_configuration.dynamic_shared_memory_size,
                        stream_id
                        >>>(parameters...);
+               cuda::outstanding_error::ensure_none("Kernel launch failed");
        }
        else {
 #if __CUDACC_VER_MAJOR__ >= 9
@@ -157,7 +158,7 @@ inline void enqueue_launch(
                        argument_ptrs,
                        launch_configuration.dynamic_shared_memory_size,
                        stream_id);
-               throw_if_error(status, "Cooperative launch failed");
+               throw_if_error(status, "Cooperative kernel launch failed");
 
 #else
```

**Comment by codecircuit** [comment]
Exactly :)

**Comment by eyalroz** [comment]
@codecircuit : I just tried sending you an email message, and got a failure note about an "SPF failure". FYI.

**Comment by eyalroz** [comment]
@codecircuit : This bug gets auto-closed when the changes land on the main branch, right now they're in development.
