### ISSUE TITLE
Including CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES messes  up the exported Config.cmake

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#121]
If we have
```
target_include_directories(cuda-api-wrappers ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
```
in `CMakeLists.txt`, the `Config.cmake` file we generate has:
```
set_target_properties(cuda-api-wrappers::cuda-api-wrappers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/path/to/source/folder/root/;${_IMPORT_PREFIX}/include"
```
i.e. it requires the source folders to exist in order to use the library. This makes no sense to me, as this happens even if `CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES` is empty! plus - those paths should have nothing to do with our source directory. 

This happened to me with CMake 3.14.3 on Devuan GNU/Linux 3.0

**Comment by codecircuit** [comment]
The commit 1a735b3b537732ba760f6acf8c3387fec1b20929 makes the include of the CUDA header files `PRIVATE`. See here https://github.com/eyalroz/cuda-api-wrappers/blob/development/CMakeLists.txt#L55 This is not correct if public header files of the target `cuda-api-wrappers` include CUDA header files like `builtin_types.h`, which is included by `cuda/api/types.hpp`. As a consequence I cannot build the sample `unified_addressing` any more.

**Comment by eyalroz** [comment]
@codecircuit :+1: 
What do you get, in the installed `cuda-api-wrappers-config.cmake` file, in the line starting with 
`set_target_properties(cuda-api-wrappers::cuda-api-wrappers`
?

And - what do you get when you make the CUDA header includes PUBLIC?

**Comment by codecircuit** [comment]
With `PUBLIC` include of the CUDA header files:

```cmake
set_target_properties(cuda-api-wrappers::cuda-api-wrappers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/opt/cuda/targets/x86_64-linux/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/opt/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/librt.so"
)
```

with `PRIVATE` include of the CUDA header files:

```cmake
set_target_properties(cuda-api-wrappers::cuda-api-wrappers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/opt/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/librt.so"
)
```

It is as expected and just adds the include directory of the CUDA header files, which is mandatory.

**Comment by eyalroz** [comment]
That's weird... I don't know what to say. In fact, the target_link_libraries() alone should be enough for the correct include paths to be added to the dependent target. Not quite sure what to do.

**Comment by codecircuit** [comment]
I also do not understand completely the problem you have with the initial message. Especially what do you mean with `/path/to/source/folder/root/`?

**Comment by eyalroz** [comment]
I mean that the installed file tells whoever uses it that they depend on the _source_ directory, not on the files we installed only.

**Comment by codecircuit** [comment]
I tried to reproduce your issue with CMake@3.14.3 on a CentOS system, but it did not work. 

If I got it right, the following steps produce your issue:

```sh
git clone https://github.com/eyalroz/cuda-api-wrappers.git ~/cuda-api-wrappers
cd ~/cuda-api-wrappers
git checkout development
vim CMakeLists.txt # make the include in line 55 PUBLIC
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=~/install ..
make -j install
vim ~/install/share/cmake/cuda-api-wrappers/cuda-api-wrappers-config.cmake # command starting in line 56 contains path to cloned repository ~/cuda-api-wrappers
```

**Comment by eyalroz** [comment]
Yes, and this gives me the following (line 56-59):
```
set_target_properties(cuda-api-wrappers::cuda-api-wrappers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/home/eyalroz/cuda-api-wrappers/;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so"
)
```

**Comment by eyalroz** [comment]
And if I make the inclusion of ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES} private, then these lines become:
```
set_target_properties(cuda-api-wrappers::cuda-api-wrappers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so"
)
```

**Comment by eyalroz** [comment]
Ok, I think I solved it. I need to drop the quotation marks enclosing the use of the variable.
