### ISSUE TITLE
Default CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#124]
In the `CMakeLists.txt` and the `examples/CMakeLists.txt` the default `CMAKE_BUILD_TYPE` is set to `Release`. I think it is recommended to stick to the CMake defaults here, which is the empty build type.

See https://blog.kitware.com/cmake-and-the-default-build-type/#comment-8726

**Comment by eyalroz** [comment]
That blog post actually does set the default build type to release:
```
# Set a default build type if none was specified
set(default_build_type "Release")
if(EXISTS "${CMAKE_SOURCE_DIR}/.git")
  set(default_build_type "Debug")
endif()
 
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  message(STATUS "Setting build type to '${default_build_type}' as none was specified.")
  set(CMAKE_BUILD_TYPE "${default_build_type}" CACHE
      STRING "Choose the type of build." FORCE)
  # Set the possible values of build type for cmake-gui
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS
    "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif()
```
The comment you linked to is about using `set_property()` within the code above. Actually, I don't quite understand what the comment is saying about "avoiding an update of the docstring".

**Comment by codecircuit** [comment]
I think this is more a question of how this package interacts with other packages or package managers. CMake has e.g. these build types: empty, debug, release, release with debug info. A build type can change the compile flags. If I type `cmake ..` I expect the CMake default build type, which is currently the empty build type. For `cuda-api-wrappers` this is not correct, since it compiles in `Release` as the default build type. That means if I set `export CUDAFLAGS=-O1` and build the `cuda-api-wrappers` with `cmake ..; make`, it will fail because the `Release` build adds `-O3` automatically.

What I want to say is, that one should have a good reason to change default behaviour. So what is your motivation to change the default build type?

**Comment by eyalroz** [comment]
Trying to follow common practice. But given the information I now have, I guess I should keep "build-type-neutral"

**Comment by eyalroz** [comment]
Done.
