### ISSUE TITLE
Introduce versioning via CMakelists.txt

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#143]
@codecircuit  - something like this? :
```
+++ b/CMakeLists.txt
@@ -13,6 +13,7 @@ endif()
 
 PROJECT(cuda-api-wrappers
        DESCRIPTION "Thin C++-flavored wrappers for the CUDA Runtime API"
+       VERSION 0.2.0
        HOMEPAGE_URL https://github.com/eyalroz/cuda-api-wrappers
        LANGUAGES CUDA CXX)
 
@@ -71,6 +72,14 @@ install(
        NAMESPACE "cuda-api-wrappers::"
        # In this CMake config file no dependencies are considered. But since we
        # do not use any `find_package` call here this approach is sufficient.
)
+
       FILE cuda-api-wrappers-config.cmake
+include(CMakePackageConfigHelpers)
+
+write_basic_package_version_file(
+       "cuda-api-wrappers-config-version.cmake"
+       VERSION ${PROJECT_VERSION}
+       COMPATIBILITY SameMinorVersion
```
?

**Comment by codecircuit** [comment]
By installation the CMake files are installed like this:

```
-- Up-to-date: INSTALLDIR//lib64/cmake/cuda-api-wrappers/cuda-api-wrappers-config.cmake
-- Up-to-date: INSTALLDIR//lib64/cmake/cuda-api-wrappers/cuda-api-wrappers-config-release.cmake
-- Up-to-date: INSTALLDIR/lib64/cmake/strf/cuda-api-wrappers-config-version.cmake
```

So the only problem is that the `cuda-api-wrappers-config-version.cmake` file ends up in the `strf` directory. It should end up in `INSTALLDIR//lib64/cmake/cuda-api-wrappers/`. Because then the `find_package(cuda-api-wrappers 0.5.0 REQUIRED)` works as expected.

**Comment by eyalroz** [comment]
Sorry, I forgot to re-add a final copy-paste correction. Have amended to commit and it's now written to the correct location.

Well, it seems I've (sort of) gotten the hang of installation with CMake - at least for this library. And it was so easy^H^H^H^H complicated...

**Comment by eyalroz** [comment]
@codecircuit : But note that the development branch is now 0.3.0, not 0.5.0.
