### ISSUE TITLE
invalid order of argumens in create_stream()

### ISSUE THREAD

**Issue by esaulenka** [eyalroz/cuda-api-wrappers#144]
The order of argumens of `create_on_current_device()` seems to be mixed up

https://github.com/eyalroz/cuda-api-wrappers/blob/d9f5a0c5230f5478f62111da7f2127858d78b354/src/cuda/api/stream.hpp#L582-L591

`synchronize` flag should be first

**Comment by eyalroz** [comment]
I think you're right.

**Comment by eyalroz** [comment]
Fixed on master and development.

**Comment by eyalroz** [comment]
By the way, @esaulenka : If you're using the wrappers in an interesting project, please let me know. Also, if you have feeback which isn't bug reports (e.g. complaints/requests/etc.)

**Comment by esaulenka** [comment]
unfortunately, I cant use it now.

I have old GPU, that not supported in recent CUDA.
I tried to build your API with MSVC 2015 (as I know, it is latest MS compiler, that integrates with CUDA 8).
There is some errors with host-part of your library. It seems that MS did not comply with C++standards in 2015.
However, it was useful:  among other things, it showed a warning in `create_on_current_device` ;-)

**Comment by eyalroz** [comment]
Well, most of my API works _without_ building it - as header-only. Just don't use the functions with C++ implementations. Also, yes, it's true that MSVC has had compliance problems - even with C++11. But it's improved by 2017.
