### ISSUE TITLE
Add non-memory-space-specific version of set() and zero()

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#145]
We have `cuda::memory::copy()`, which determines which memory space each argument is in and acts accordingly. Should we not also have this for `set()` and `zero()`? Currently, they only exist for specific memory spaces which you have to specify explicitly at compile-time.  This way we will both memory-space-specific `set(), zero(), copy()` and general variants of all three.

One significant reason could be the fact that the CUDA runtime API itself supports the generalized copy variant, but not a generalized set or zero variant. So... would users be willing to to live with us doing a bit of behind-the-scenes work to determine which space a pointer belongs in?

**Comment by codecircuit** [comment]
Keep in mind that it is sometimes desireable to specify the execution policy (host or device) of these functions. Especially if you consider managed memory. Thus an additional function, which determines the memory space of a pointer , should not replace the functionality of the already existing functions, but extent them.

**Comment by eyalroz** [comment]
@codecircuit : Naturally; edited to clarify. But - as an _additional_ function - what do you think?

**Comment by codecircuit** [comment]
That is a good idea :+1:

**Comment by eyalroz** [comment]
Ok, it's decided.
