### ISSUE TITLE
De-templatize streams and devices

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#147]
Following the discussion in issue #142 , I've decided it is better to simplify the API and its use by dropping the templated "assume current device" versions of streams and devices, and have them simply _not_ assume they're current. 

The cost: 

* More `cudaSetDevice()` calls - especially on systems with a single device, where one might write an app using the current device solely.
* A few more `cudaGetDevice()` calls.

The benefit:

* Prevents the error of users assuming that they can go ahead and use streams created with an assumption their device is current, with other stream which do not.
* Users do not need to template their stream- and device-handling code based on whether it's the current device or not (although TBH that was achievable before).
* Users do not need to remember to add empty template brackets everywhere (`stream_t<>`).
* Reduces (but not removes entirely the re-entrancy of the device and stream classes (e.g. what happens when some other thread changes the current DB and thread?)

**Comment by eyalroz** [comment]
@codecircuit : How do you like these changes?

**Comment by codecircuit** [comment]
I love them <3

**Comment by eyalroz** [comment]
@codecircuit : And have you actually used them in your code? Unfortunately, the examples only use a part of the API, so I need a bit of usage feedback (other than from my own code) to feel safe about such a significant change, before merging back to master.

**Comment by codecircuit** [comment]
Ok, I will soon integrate the changes.

**Comment by eyalroz** [comment]
@codecircuit : ping. I'm thinking of creating a new release following these changes, which is why I've been anxious for your input as well.

**Comment by codecircuit** [comment]
I start tomorrow then. Until the end of the week this should be done :+1:

**Comment by codecircuit** [comment]
To me this looks fine :+1:
