### ISSUE TITLE
Kernel launch still takes stream ID instead of stream object

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#157]
Regarding #31 one should rather write

```cpp
cuda::enqueue_launch(..., stream, ...);
```
instead of

```cpp
cuda::enqueue_launch(..., stream.id(), ...);
```

I think latter is still needed.

**Comment by eyalroz** [comment]
(sigh) I missed that one... took quite a few changes to set right, actually. Should be ok now.
