### ISSUE TITLE
CMake 3.17 automatically adds Threads::Threads as interface library

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#160]
The cuda-api-wrappers library depends on PThreads, which is now handled as a separate target in CMake. Thus if you just include the cuda-api-wrappers in your own CMake project CMake complains about the missing Target `Threads::Threads`. This dependency is not just a 'nice-to-have' dependency because PThreads is used in the compiled part of the wrappers and not just in one stand alone header.

Helpful for that is the CMake module `CMakeFindDependencyMacro`. If you need help with this I can create a PR.

**Comment by eyalroz** [comment]
* "now handled" = with CMake 3.17?
* There's a dependency on pthreads only on Unix-like systems. On Windows, we depend on wherever `processthreadsapi.h` comes from.

**Comment by eyalroz** [comment]
Something like this?:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8fa35fa..37d2da4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -19,6 +19,8 @@ PROJECT(cuda-api-wrappers
 
 include(FindCUDA) 
 include(GNUInstallDirs)
+set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
+include(FindThreads REQUIRED)
 
 set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "lib/")
 set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "lib/")
@@ -28,10 +30,24 @@ add_library(cuda-api-wrappers
 	src/cuda/api/profiling.cpp
 )
 
+target_link_libraries(cuda-api-wrappers
+	PUBLIC
+	Threads::Threads
+)
+
 set_property(TARGET cuda-api-wrappers PROPERTY CXX_STANDARD 11)
 set_property(TARGET cuda-api-wrappers PROPERTY CXX_STANDARD_REQUIRED ON)
 set_property(TARGET cuda-api-wrappers PROPERTY CXX_EXTENSIONS OFF)
 
+if(DEFINED CMAKE_USE_PTHREADS_INIT)
+	target_compile_definitions(cuda-api-wrappers PUBLIC "CUDA_API_WRAPPERS_USE_PTHREADS")
+else()
+if(DEFINED CMAKE_USE_WIN32_THREADS_INIT)
+	target_compile_definitions(cuda-api-wrappers PUBLIC "CUDA_API_WRAPPERS_USE_WIN32_THREADS")
+endif()
+endif()
+
+
 target_include_directories(
 	cuda-api-wrappers
 	PUBLIC
@@ -83,9 +99,7 @@ write_basic_package_version_file(
 	COMPATIBILITY SameMinorVersion
 )
 
-
 install(
   FILES "${CMAKE_CURRENT_BINARY_DIR}/cuda-api-wrappers-config-version.cmake"
   DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/cuda-api-wrappers"
 )
-  
diff --git a/src/cuda/api/profiling.cpp b/src/cuda/api/profiling.cpp
index 1f9209c..36d1184 100644
--- a/src/cuda/api/profiling.cpp
+++ b/src/cuda/api/profiling.cpp
@@ -12,13 +12,13 @@
 
 #include <mutex>
 
-#ifdef __unix__
+#ifdef CUDA_API_WRAPPERS_USE_PTHREADS
 #include <pthread.h>
 #else
-#ifdef _WIN32
+#ifdef CUDA_API_WRAPPERS_USE_WIN32_THREADS
 #include <processthreadsapi.h>
-#endif // _WIN32
-#endif // __unix__
+#endif
+#endif
 
 namespace cuda {
 namespace profiling {
```

**Comment by codecircuit** [comment]
These changes look fine :+1:. But one problem is still that if you include the `cuda-api-wrappers` in your CMake project the `cuda-api-wrappers-config.cmake` only shows the link to `Threads::Threads`, but does not include any `find_dependency(Threads)`. The result is that you must include the wrappers like this:

```cmake
find_package(Threads REQUIRED)
find_package(cuda-api-wrappers REQUIRED)
```

but instead you want to include them just with one line including every dependency of the wrappers

```cmake
find_package(cuda-api-wrappers REQUIRED) # also finds package Threads
```

To achieve that I recommend to rename `cuda-api-wrappers-config.cmake` to `cuda-api-wrappers-targets.cmake` and to set the content of `cuda-api-wrappers-config.cmake.in` to:

```cmake
# Get the directory containing this file.
get_filename_component(@PROJECT_NAME@_CURRENT_CONFIG_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

include(CMakeFindDependencyMacro)

find_dependency(ThreadsREQUIRED)

# Import targets.
include("${@PROJECT_NAME@_CURRENT_CONFIG_DIR}/@PROJECT_NAME@-targets.cmake")
```

Then you can create `cuda-api-wrappers-config.cmake` with `configure_file`.

**Comment by eyalroz** [comment]
So, if I do this, what happens to the:
```
+include(FindThreads REQUIRED)
```
line I have in CMakeLists.txt right now?

**Comment by eyalroz** [comment]
... and another issue with your suggestion: If my `install(EXPORT)` command writes `cuda-api-wrappers-targets.cmake`, then the installation will have`cuda-api-wrappers-targets-noconfig.cmake` rather than `cuda-api-wrappers-config-noconfig.cmake`. What do I do about that?

**Comment by codecircuit** [comment]
I do not understand the idea with the `-noconfig` files. Can you explain this in more detail?

**Comment by eyalroz** [comment]
@codecircuit : When installing a project, a(n extra) configuration file gets created with the name of your build type: `-release.cmake`, `-debug.cmake` or `-noconfig.cmake`.

**Comment by codecircuit** [comment]
As far as I see it you, after installing Debug and Release build type you have these files installed:

- `cuda-api-wrappers-config.cmake` always equal
- `cuda-api-wrappers-targets.cmake` always equal and includes every `cuda-api-wrappers-targets-*.cmake` file
- `cuda-api-wrappers-targets-debug.cmake`
- `cuda-api-wrappers-targets-release.cmake`

So that should be okay, right?

**Comment by eyalroz** [comment]
If `-target.cmake` includes the different build-type-specific files then yes, but - does it?

**Comment by eyalroz** [comment]
Ok, I see it now:
```
# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/cuda-api-wrappers-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()
```
fine then.

**Comment by codecircuit** [comment]
I just saw that the the line with

```cmake
include(CMakeFindDependencyMacro)
```

was removed in `cmake/cuda-api-wrappers-config.cmake.in`. What was the reasoning for that? I think it can happen that the Macro `find_dependency` is not found if we omit the include.

Why is the dependency to `Threads::Threads` `PUBLIC`? I think it should be enough to mark the dependency as `PRIVATE` because no header includes something of the `Threads` package. And thus it is only required for linking.

**Comment by eyalroz** [comment]
> I just saw that the the line with
> 
> ```cmake
> include(CMakeFindDependencyMacro)
> ```
> 
> was removed in `cmake/cuda-api-wrappers-config.cmake.in`. What was the reasoning for that? I think it can happen that the Macro `find_dependency` is not found if we omit the include.

A mistake. It has a non-interesting explanation; will restore it.


> Why is the dependency to `Threads::Threads` `PUBLIC`? I think it should be enough to mark the dependency as `PRIVATE` because no header includes something of the `Threads` package. And thus it is only required for linking.

Required for linking = required. So, it's PUBLIC.

**Comment by codecircuit** [comment]
CMake started to support `find_package(CUDAToolkit)`: https://cmake.org/cmake/help/v3.17/module/FindCUDAToolkit.html

just If you want to update the required CMake version at some point.

**Comment by codecircuit** [comment]
I am very sure that the link to `Threads::Threads` should be `PRIVATE`. You can also verify this easily by yourself when you check the `cuda-api-wrappers-targets.cmake` file. If you make the link `PRIVATE` you will find this line:

```
  INTERFACE_LINK_LIBRARIES "/opt/cuda/lib64/libcudart_static.a;Threads::Threads;dl;/usr/lib/librt.so;\$<LINK_ONLY:Threads::Threads>"
```

The first link to `Threads::Threads` is still `PUBLIC` due to the fact that `Threads::Threads` is included in `${CUDA_LIBRARIES}`, which is populated by the deprecated find module `include(FindCUDA)`. If you use `find_package(CUDAToolkit)` and later link to `CUDA::cudart` the make the link to `Threads::Threads` `PRIVATE` you will see in `cuda-api-wrappers-targets.cmake`:

```
  INTERFACE_LINK_LIBRARIES "CUDA::cudart;\$<LINK_ONLY:Threads::Threads>"
```

which is exactly what we want. If you subsequently link against `cuda-api-wrappers` in another project PThreads is included at linking step as expected.

**Comment by eyalroz** [comment]
> just If you want to update the required CMake version at some point.

Not for a good several years - when most Linux distributions have it...

**Comment by eyalroz** [comment]
@codecircuit: I guess I'll take your word for it. At worst, someone will report a bug...
