### ISSUE TITLE
Probably some undefined behaviour with `cuda::device_function_t`

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#161]
This sample:

```cpp
#include <iostream>

#include <cuda/api_wrappers.hpp>

template<class F>
__global__
void kernel(F f) {
	printf("f.a = %f\n", f.a);
}


struct Functor {
	float a = 7.0;
};

int main() {

	auto native_kernel = kernel<Functor>;
	cuda::device_function_t wrappers_kernel = kernel<Functor>;
	Functor f;
	auto device = cuda::device::current::get();
	std::cout << "launch native kernel" << std::endl;
	cuda::launch(native_kernel, cuda::make_launch_config(1, 1), f);
	device.synchronize();
	std::cout << "launch wrappers kernel" << std::endl;
	cuda::launch(wrappers_kernel, cuda::make_launch_config(1, 1), f);
	device.synchronize();
}
```

produces on my machine this result:

```
launch native kernel
f.a = 7.000000
launch wrappers kernel
f.a = 1128556307164528451843522560.000000
```

Neither `valgrind` nor `cuda-memcheck` report any error on that. Any ideas?

**Comment by eyalroz** [comment]
1. Maybe it has to do with the synchronization policy? See [here](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gd228014f19cc0975ebe3e0dd2af6dd1b)
2. Have you tried "unwrapping the wrappers" and seeing if you get the result? i.e. maybe it is "not my fault (TM)"

**Comment by codecircuit** [comment]
I did the unwrapping and everything works fine. I do not think it has something to do with synchronization. I further simplified the snippet. Please have a look at it. Did you try to compile and execute it?

**Comment by codecircuit** [comment]
The last commit is the reason for this behaviour. If you go back to d8622629b423bbc7011557e499c46ddd7e5fb48b everything works fine.

**Comment by eyalroz** [comment]
> I did the unwrapping and everything works fine. 

Doesn't that mean you unwrapped incorrectly?

> The last commit is the reason for this behaviour. If you go back to d862262 everything works fine.

Will check.

**Comment by eyalroz** [comment]
Try it now.

**Comment by codecircuit** [comment]
fixed

**Comment by codecircuit** [comment]
Sry, I accidentally closed this issue. If you want to keep this issuo open until the next merge into master, please reopen.
