### ISSUE TITLE
How to handle cudaCpuDeviceId in prefetches

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#164]
With `cudaMemPrefetchAsync` you can also prefetch pages to the host with `cudaCpuDeviceId` as a device ID. The current `prefetch` function of the wrappers, which is not in the `detail` namespace requires the device to be a `cuda::device_t`. As far as I see it, there is no way to get a `cuda::device_t` object, which represents the host. Thus you must use the `detail::prefetch` function. But as a user of a library you should not depend on functions in `detail`, right?

**Comment by eyalroz** [comment]
Wait, the CPU has a device ID? :-O

... need to look into this conundrum.

**Comment by eyalroz** [comment]
How about a class which is a poor man's variant, for either a CPU or a CUDA device? So that a CPU can't be used as a `cuda::device_t`, on one hand; and people can't start brandishing these structures all over the placd
