### ISSUE TITLE
Why is device_memory case ignored for the cuda::memory::set()?

### ISSUE THREAD

**Issue by neoblizz** [eyalroz/cuda-api-wrappers#178]
Shouldn't this also call `memory::device::set(buffer_start, byte_value, num_bytes);`?

https://github.com/eyalroz/cuda-api-wrappers/blob/b33726d4cd72760fbd9d06c370e5fd5ee59c7d31/src/cuda/api/memory.hpp#L253-L265

**Comment by eyalroz** [comment]
It is making that call. There's fall-through between switch cases. Unless I misunderstood your question?

**Comment by eyalroz** [comment]
Note that with C++17, it is now customary to write [`[[fallthrough]]`](https://en.cppreference.com/w/cpp/language/attributes/fallthrough) in these cases, to make the intention explicit.

**Comment by neoblizz** [comment]
Oops, I misread. Explicit `[[fallthrough]]` would be nice, but it works. Thanks~
