### ISSUE TITLE
device properties arch values should be dependent on the compute capability not general architectures.

### ISSUE THREAD

**Issue by neoblizz** [eyalroz/cuda-api-wrappers#183]
Take this for example:
```
{ 1,  16 * KiB },
{ 2,  48 * KiB },
{ 3,  48 * KiB },
{ 5,  48 * KiB },
{ 6,  48 * KiB },
{ 7,  96 * KiB },
```
What you really have is:

- Fermi
  - 2, 2.1
- Kepler
  - 3, 3.2, 3.5, 3.7 
- Maxwell
  - 5, 5.2, 5.3
- Pascal
  - 6, 6.1, 6.2
- Volta
  - 7, 7.2
- Turing
  - 7.5
- Ampere
  - 8

Right now, device properties is unusable for me because the minor versions often have important code breaking differences.

**Comment by eyalroz** [comment]
Arch regards the major number in the compute capability number-pair. Use the compute-capability class to get both numbers. There's a [method for it](https://codedocs.xyz/eyalroz/cuda-api-wrappers/structcuda_1_1device_1_1properties__t.html) in the `device::properties_t` class. Doesn't that work for you?

**Comment by neoblizz** [comment]
I didn't notice the fallback to architecture values 🤦‍♂️. This works, now the only issue really is #182.
