### ISSUE TITLE
Incorrect fallback architecture functions for cc device properties

### ISSUE THREAD

**Issue by neoblizz** [eyalroz/cuda-api-wrappers#184]
Minor fix is needed: https://github.com/eyalroz/cuda-api-wrappers/blob/4dd982a8d6ec9c65430fc5675f54b395dd5a412d/src/cuda/api/detail/device_properties.hpp#L227-L261 all fallback to `max_in_flight_threads_per_processor(cc.architecture)`, when they should fallback to the corresponding property.

**Comment by eyalroz** [comment]
1. Give me an example for which the result is incorrect.
2. There is no such property AFAICR, otherwise I wouldn't have written this myself.
3. The idea here as that, typically, the values are uniform for each architecture (major number), with a few exceptions. That's why the fallback is appropriate.

**Comment by neoblizz** [comment]
I think you misunderstood. The idea is correct, fallback should happen. But out of the 4 functions above all of them default fallback to `max_in_flight_threads_per_processor` instead of their respective fallback functions, for example, the `max_warp_schedulings_per_processor_cycle` below is fallbacks to `max_in_flight_threads_per_processor` instead of `max_warp_schedulings_per_processor_cycle`.

```cpp
 inline constexpr unsigned max_warp_schedulings_per_processor_cycle(const compute_capability_t& cc) 
 { 
 	return 
 		cc.as_combined_number() == 61 ? 4 : 
 		cc.as_combined_number() == 62 ? 4 : 
- 		max_in_flight_threads_per_processor(cc.architecture); 
+		max_warp_schedulings_per_processor_cycle(cc.architecture); 
 } 
```

Hope that makes more sense.

**Comment by eyalroz** [comment]
Oh, oh, right. Sorry. I'll amend the previous patch in a couple of minutes.
