### ISSUE TITLE
Should we rename device_function_t into kernel_t?

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#187]
@codecircuit , I'd like your opinion on this...

`device_function_t` is a bit of a misnomer. It can't be used for any device-side function - only for kernels (`__global__`). And with issues #186 resolved and #185 hopefully coming up, it's become a beefier class. Do you think it's legitimate to "endow" it with the name of `kernel_t`?

One argument against could be that a `kernel_t` class should perhaps have more machinery, e.g. a-priori or just-before-launch computation of an appropriate launch configuration - not just what we get with `cudaOccupancyMaxPotentialBlockSize()`. On the other hand, that sort of thing might be too  much of an abstraction for the API wrappers as such; and we may not want to force whoever instantiates a `kernel_t` to have to know how to compute a good launch config.

**Comment by codecircuit** [comment]
I think calculating a "good" kernel launch configuration is a non-trivial task. As such this should be left to the user. What you mentioned is to include the kernel launch configuration in the `kernel_t` class, right?

The renaming sounds reasonable to me, because in the CUDA terminology a device function is associated with a `__device__ ReturnType function(...) {...}`, which is not a kernel.

**Comment by eyalroz** [comment]
> I think calculating a "good" kernel launch configuration is a non-trivial task. As such this should be left to the user.

Of course that should be left to the user, but then - so is providing the actual kernel. The question is whether constructing a kernel should require both the `__global__` function pointer and an invocable object - provided by the user - which computes a launch configuration.

Anyway, The second paragraph of your answer sounds like a "yes". So I'll ponder this a while longer and probably do the rename. I plan to make a 0.3 release soon - before doing work on #176 which will change the structure of the repository somewhat.
