### ISSUE TITLE
Qualifiers cast away in kernel.hpp

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#208]
https://github.com/eyalroz/cuda-api-wrappers/blob/47d77610146deee53c05f674630a4250ce6be7cb/src/cuda/runtime_api/kernel.hpp#L299

If you want to use the wrappers with `clang` I get the following error:

```shell
cuda-api-wrappers/src/cuda/api/kernel.hpp:299:9: error: reinterpret_cast from 'const void *' to 'raw_kernel_t' (aka 'void (*)(const float *, const float *, const float *, thrust::zip_iterator<thrust::tuple<const float *, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, float *, float *, float *, thrust::zip_iterator<thrust::tuple<float *, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >, const int *, const unsigned long, float)') casts away qualifiers
        return reinterpret_cast<raw_kernel_t>(wrapped.ptr());
```

Probably that happens because the `const` should be cast away. It worked for me to change the corresponding line to:

```cpp
	return reinterpret_cast<raw_kernel_t>(const_cast<void*>(wrapped.ptr()));
```

**Comment by eyalroz** [comment]
I guess I could do something like that. Although maybe I could just make raw_kernel_t a const pointer.

...

wait, I can't reproduce this. I'm compiling the examples with clang++-10 and not getting this message. Can you provide a minimal example and a compiler invocation line?

**Comment by r-burns** [comment]
I'm seeing this as well. Using clang++-10, CMake 3.18, and CUDA Toolkit 11, my compile line is:
```
cd /home/user/personal/cuda-api-wrappers/build-clang/examples && /usr/bin/clang++  -DCUDA_API_WRAPPERS_USE_PTHREADS -I/home/user/personal/cuda-api-wrappers/src -Xcompiler -Wall --cuda-gpu-arch=sm_52 --cuda-path=/opt/cuda -std=c++11 -x cuda -c /home/user/personal/cuda-api-wrappers/examples/modified_cuda_samples/p2pBandwidthLatencyTest/p2pBandwidthLatencyTest.cu -o CMakeFiles/p2pBandwidthLatencyTest.dir/modified_cuda_samples/p2pBandwidthLatencyTest/p2pBandwidthLatencyTest.cu.o
```
Error is
```
/home/user/personal/cuda-api-wrappers/src/cuda/api/kernel.hpp:299:9: error: reinterpret_cast from 'const void *' to 'raw_kernel_t' (aka 'void (*)(int4 *, int4 *, unsigned long)') casts away qualifiers
        return reinterpret_cast<raw_kernel_t>(wrapped.ptr());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Described fix works for me

**Comment by eyalroz** [comment]
@r-burns : Ok, I see now. I changed my CXX and reconfigured CMake, but it only picked up clang++ for the .cpp files. Reproducing now.

See also [this question](https://stackoverflow.com/q/62961212/1593077) I just asked over on StackOverflow.

**Comment by r-burns** [comment]
Yeah, should have specified that I'm using clang as CUDACXX there. I've made a few tweaks in my clang-cuda branch if you'd like to try out the cmake clang cuda support.

**Comment by eyalroz** [comment]
@r-burns : Oh yes, certainly. I'd appreciate a PR. Maybe I should try and add some Travis build machine configurations for this.

**Comment by r-burns** [comment]
From what I can tell, POSIX explicitly allows conversions between function pointers and void*, but doesn't mention const void*. Maybe gcc/nvcc takes a broader interpretation of that than clang.

I'll send in a PR shortly. Would you prefer it vs master or vs development? I see you already pushed a warning fix for clang to development, but nothing strictly necessary to get a working build.

**Comment by eyalroz** [comment]
@r-burns : Against development, please. I do all work there, then merge into master for releases.
