### ISSUE TITLE
Multiple definition of `cuda::kernel_t::min_grid_params_for_max_occupancy(unsigned int, unsigned int, bool)' 

### ISSUE THREAD

**Issue by szsdk** [eyalroz/cuda-api-wrappers#216]
Do you think adding an `inline` to https://github.com/eyalroz/cuda-api-wrappers/blob/78213e48f9b951fcb3813d15fadbf2cea9cfe727/src/cuda/api/multi_wrapper_impls.hpp#L383-L384 would be a good idea?

**Comment by eyalroz** [comment]
Yes, this slipped by me somehow.
