### ISSUE TITLE
Segmentfault caused by memory layout

### ISSUE THREAD

**Issue by szsdk** [eyalroz/cuda-api-wrappers#217]
This code raises segmentation fault but works after changing the memory layout of class `B` by swapping the position of `tex_view` (a unique pointer) and `data`.
```cuda
#include <cuda/api_wrappers.hpp>

struct B
{
    int size{16};
    cuda::texture::descriptor_t texDescr{};
    // Swapping the next two lines makes things work.
    std::unique_ptr<cuda::texture_view> tex_view;
    cuda::array_t<float, 3> data;
    B(): data(cuda::array_t<float, 3>(
                cuda::array::detail::allocate_on_current_device<float>(cuda::array::dimensions_t<3>(size, size, size)),
                cuda::array::dimensions_t<3>(size, size, size)
                )),
    texDescr(cuda::texture::descriptor_t()),
    tex_view(std::make_unique<cuda::texture_view>(data, texDescr))
    {}
};

int main()
{
    B b{};
    return 0;
}
```

I have tested this with Cuda 10.2 on GTX980 and Cuda 9.2 on GTX1080, which gave the same results. A strange bug. I am not even sure whether it is a bug of this package or somewhere deeper.

**Comment by r-burns** [comment]
I'd guess this is just due to member initialization order. In the order you have it, `tex_view` gets initialized first, and gets passed an uninitialized `data`.

**Comment by szsdk** [comment]
> I'd guess this is just due to member initialization order. In the order you have it, `tex_view` gets initialized first, and gets passed an uninitialized `data`.

You are right. I found out that I have misunderstood this for a long time.

**Comment by eyalroz** [comment]
@szsdk : Based on your latest comment, I'm closing this issue.
