### ISSUE TITLE
driver-api branch failing on Travis CI - CUDA_CUDA_NOUTFOUND

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#227]
When trying to build the new driver-API-supporting branch, the Travis CI machines fail, complaining about not finding the CUDA libray:
```
/usr/bin/g++   -Wall -Wextra -Wpedantic -Wno-missing-field-initializers -O3 -DNDEBUG   CMakeFiles/version_management.dir/by_runtime_api_module/version_management.cpp.o  -o bin/version_management /usr/local/cuda-9.2/lib64/libcudart_static.a -lpthread -ldl /usr/lib/x86_64-linux-gnu/librt.so -lCUDA_CUDA_LIBRARY-NOTFOUND 

/usr/bin/ld: cannot find -lCUDA_CUDA_LIBRARY-NOTFOUND

collect2: error: ld returned 1 exit status
```
We need to get CMake on those machines to find the library.

**Comment by eyalroz** [comment]
Trying the approach [here](https://github.com/opencv/opencv/issues/6577): Add CUDA's stubs library to the search path.

**Comment by r-burns** [comment]
Looks correct, similar to the approach in the more modern FindCUDAToolkit module
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.18.3/Modules/FindCUDAToolkit.cmake#L773

**Comment by eyalroz** [comment]
@r-burns : Just to clarify though - this has no effect on the release or the main development branch. I was basically talking to myself :-)  ... I haven't even added any example programs which use the driver API directly, so this branch is super-volatile anyway.

**Comment by eyalroz** [comment]
Well, now
