### ISSUE TITLE
enqueue_launch with rvalue of stream

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#230]
Maybe it would be nice to support cases like:

```cpp
cuda::enqueue_launch(kernel, device.default_stream(), launch_cfg, a, b c);
```

I think this does not compile currently, because a reference of a stream object is expected.

**Comment by eyalroz** [comment]
1. This compiles and runs on the driver-API branch.
2. Will backport the availability of copy ctor, that should probably do it.

**Comment by eyalroz** [comment]
Made `stream_t&` parameters into `const stream_t&`, almost universally.
