### ISSUE TITLE
Allowing the wrappers to work with HIP

### ISSUE THREAD

**Issue by abduld** [eyalroz/cuda-api-wrappers#235]
Hi, I find these wrappers very useful. I am wondering if you thought about making it work with hipify so that they can be used with the hip rocm stack from AMD.

**Comment by eyalroz** [comment]
@abduld : But these are wrappers for CUDA. They're not supposed to be cross-vendor. They don't even support OpenCL.

That being said - if someone wants to collaborate with me on expanding these into a set of APIs which supports CUDA and rocm, or CUDA and OpenCL, I might be open to that.
