### ISSUE TITLE
Build error with CUDA 11.2 & MSVC 16.8

### ISSUE THREAD

**Issue by TheCleanCoda** [eyalroz/cuda-api-wrappers#237]
Hi, I'd like to use the api wrappers on a Windows targeted application, however I was neither able to build the examples using CMake nor my own application when using the API wrappers (a mere include of `cuda/runtime_api.hpp` already leads up to compilation errors).

Configuration:
* Win10 x64
* MSVC ~~16.8.4~~ 19.28.29336, Visual Studio 16.8.4
* CUDA 11.2
* CMake 3.19.4

Steps to reproduce: 
I cloned version v0.4 of the repo and performed two slight modifications regarding CMake variables to allow compilation using MSVC:
1. Add variable `CMAKE_CUDA_ARCHITECTURES` and set it to `52`, otherwise the CMake generation will fail with `BUILD_EXAMPLES` enabled
2. Add `/Zc:__cplusplus` to `CMAKE_CUDA_FLAGS*` (`-Xcompiler="*other flags* /Zc:__cplusplus"`), otherwise the predefined macro `__cplusplus` [will always report `199711L`](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) and a `static_assert` will be hit `runtime_api.hpp(11): static_assert(__cplusplus >= 201103L, "The CUDA Runtime API headers can only be compiled with C++11 or a later version of the C++ language standard");`

The `nvtx` project may now be built without any errors, the example projects however are failing.
The compilation log for `vectorAdd` is [attached](https://github.com/eyalroz/cuda-api-wrappers/files/5939545/build.log), the main cause for trouble seems to be:
```
1>cuda/api/memory.hpp(1030): error : template instantiation resulted in unexpected function type of "__nv_bool (cuda::memory::managed::region_t, cudaMemRangeAttribute)" (the meaning of a name may have changed since the template declaration -- the type of the template is "T (cuda::memory::region_t, cudaMemRangeAttribute)")
1>          detected during instantiation of "cuda::memory::managed::detail::get_scalar_range_attribute" based on template argument <__nv_bool>
1>(1030): here
```

I'm a little lost on this one. Any suggestions?
Thanks in advance for any support.

**Comment by eyalroz** [comment]
Well, about CMAKE_CUDA_ARCHITECTURES - that gets auto-filled if you set the minimum CMake version to 3.18 or later. But that's not what needs to happen... see issue #238 which I've just opened. If you check out the developement branch of cuda-api-wrappers, do you still see an error related  to CMAKE_CUDA_ARCHITECTURES? Please comment on that bug.

About the `__cplusplus` macro and MSVC: Does this depend on the choice of MSVC version? That is, would we also see this issue with more recent MSVC versions?

**Comment by TheCleanCoda** [comment]
@eyalroz Thanks for your answer.
I can verify that with the development branch no `CMAKE_CUDA_ARCHITECTURES` have to be defined, generation of the CMake project works.

The build of the generated projects however is still failing (one build error related to the C++ std version which can be solved with the `/Zc:__cplusplus` build-flag and one build error regarding the template instantiation as stated in the first post)
I'm on the latest MSVC version. Regarding to [this blogpost](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/) the `__cplusplus` macro will always evaluate to `199711L` with MSVC as long as the `/Zc:__cplusplus` flag is not set.

The tough problem to solve still is the template error `cuda/api/memory.hpp(1030): error : template instantiation resulted in unexpected function type of "__nv_bool (cuda::memory::managed::region_t, cudaMemRangeAttribute)" (the meaning of a name may have changed since the template declaration -- the type of the template is "T (cuda::memory::region_t, cudaMemRangeAttribute)")`

**Comment by TheCleanCoda** [comment]
#239: Created a PR to resolve the error relating the `__cplusplus` macro.

**Comment by eyalroz** [comment]
So, now that we have the two other problems aside - you're still seeing that last error message, right? Which example triggers it?

**Comment by TheCleanCoda** [comment]
Yes, that's true. When compiling the other examples a lot of other build errors are emitted (caused by a limited set of functions).
The cause are mainly invalid casts of unrelated types and a missing include. I was able to fix the errors, I'm however unsure whether the changes are semantically correct.
Can you please review the changes in following patch:

[fix-v1.zip](https://github.com/eyalroz/cuda-api-wrappers/files/5944354/fix-v1.zip)

**Comment by eyalroz** [comment]
Ok, there 3 changes here:

1.  Missing inclusion of `<tuple>` in `stream.hpp`. Yes, that is missing. With libstdc++/libc++ , it must already be included someplace else. Accepted.
2.
    ```
-       using attribute_t = device::attribute_t;
+       using attribute_t = cudaDeviceAttr;
    ```
    this is a bit problematic for me. It is important that `device::attribute_t` be the same type as `device_t::attribute_t`. Although, frankly... I don't even remember why I need that type in he first place. Maybe I can just remove it, and use `device::attribute_t`? ... looks like I can. Does that work for you?
3. 
    ```
    -inline T get_scalar_range_attribute(region_t region, cudaMemRangeAttribute attribute)
    +inline T get_scalar_range_attribute(cuda::memory::region_t region, cudaMemRangeAttribute attribute)
    ```
    will rework this differently.

**Comment by eyalroz** [comment]
@TheCleanCoda : Please confirm that the development branch is now free of the issues you mentioned here (and close the bug).

Note you will need to force-pull, since some commits have changed.

If MSVC complains about anything else - as a warning or as an error - feel free to open a new issue. Also consider updating your MSVC...

Finally - if you have any appveyor or Travis experience, please email me.

**Comment by TheCleanCoda** [comment]
Good news: it works like a charm now 😊
Thanks a lot for your support.

Regarding the MSVC version: I wrongly stated that I'm using MSVC 16.8.4, actually the Visual Studio version is 16.8.4 and the MSVC version is 19.28.29336, which are both the latest (non-preview) versions available atm. Updated the initial post accordingly.

**Comment by eyalroz** [comment]
@quxflux : I think that it may no longer work like a charm... at least, GitHub actions is having trouble with the build, giving me 10,000 or more log lines. Would you mind trying out the latest release?

**Comment by quxflux** [comment]
@eyalroz I verified that the build fails with the latest revision on `master`. I've created a PR to fix the build error.
About 15000 of the 19000 generated warnings seem to come right out of the cuda api headers, which is caused by adding `-Wall` `CMAKE_CUDA_FLAGS`. Unfortunately I do not know about an easy way to fix this (something like a flag for `nvcc` to disable warning for the cuda api dir would be favorable)...

**Comment by eyalroz** [comment]
@quxflux  : Can you please check the development branch?

**Comment by quxflux** [comment]
@eyalroz `development` builds just fine on my machine with a tiny amount of four warnings 🙂

**Comment by eyalroz** [comment]
@quxflux : In that case, what you're really telling me is to just land development on master. Which for me means making another release.
