### ISSUE TITLE
CMake 3.18 and later complain about lack of CUDA_ARCHITECTURE setting

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#238]
When we build the examples with CMake 3.18 or later (and CUDA 11.2, possibly any CUDA 11.x), we get the following during configuration:
```
CMake Warning (dev) in examples/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "io_compute_overlap_with_streams".
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Indeed, we set the nvcc architecture-related flags "ourselves". That is, we use an older CMake facility to detect the relevant architectures, then build the nvcc flags for them ourselves. We could indeed rely on what CMake provides... but only if we could rely on using CMake 3.18 or later. Which we do not. So, let's set that policy CMP0104 for now.

**Comment by TheCleanCoda** [comment]
Testing with CMake 3.19.4 on Windows the warning is gone with c687a7940d2311a09eea1e78d87808c16807cda5.
