### ISSUE TITLE
Can't compile with many versions of MSVC due to invalid __cplusplus value

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#240]
Until recently (or perhaps even now), Microsoft's Visual C++ Compiler (MSVC) did not set the `__cplusplus` macro properly, preventing standards-compliant C++ code from determining what version of the language standard the compiler was using. MSVC was always defining it to be `199711L`.

Recently, MSVC introduced a `/Zc:__cplusplus` switch, which, when used, sets `__cplusplus` correctly. @TheCleanCoda has encountered this issue, among others (see #237), and has suggested introducing this switch using CMake; that is PR #239.

I would rather resolve this within the code itself, so as to be compatible with older versions of MSVC, which do not have this switch, but do support C++11.

Here's a patch with this solution, to apply and test:

[fix-v1.diff.zip](https://github.com/eyalroz/cuda-api-wrappers/files/5943482/fix-v1.diff.zip)

**Comment by TheCleanCoda** [comment]
@eyalroz I like this solution better than the CMake modifcation I suggested 😉.
Tested the patch, unfortunately there are compilation errors.
```
static_assert(
	__cplusplus >= 201103L or (defined(_MSVC_LANG) && _MSVC_LANG >= 201103L),
	"The CUDA Runtime API headers can only be compiled with C++11 or a later version of the C++ language standard");
```
`types.hpp(22,25): error C2146: syntax error: missing ')' before identifier 'or'`

Problem is the mix of `static_assert` with (undefined) preprocessor macros. There seems to be no inherent benefit in using a `static_assert` over a preprocessor check and letting the compilation fail using the `#error` directive as in the attached patch.

[fix-v2.zip](https://github.com/eyalroz/cuda-api-wrappers/files/5943594/fix-v2.zip)
