### ISSUE TITLE
region_t and const pointers

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#250]
Consider the case you want to do a prefetch on managed memory within this function:

```cpp

void f(const double* ptr, ..., size_t N) {
cuda::memory::managed::region_t region;
region.start = ptr; // impossible because we cannot cast `const double*` to `void*`
region.size_in_bytes = N * sizeof(double);
cuda::memory::managed::prefetch_to_host(region);
}
```

Do you think it is reasonable to support prefetches on `const` data, because CUDA also supports it? The signature is `cudaMemPrefetchAsync(const void* ptr, ...)`. Currently a `const_cast` is needed in the snippet above.

**Comment by eyalroz** [comment]
Hmm. This is one of those cases where you want to have implicit const'ification of the referent rather than the reference. I've just asked [this](https://stackoverflow.com/q/66537282/1593077) on StackOverflow.

**Comment by eyalroz** [comment]
If I don't find a better alternative, I'll probably need to define a `const_region_t`, and conversion operators :-(

**Comment by eyalroz** [comment]
@codecircuit : Would you care to comment on the new region classes? For managed and regular memory?

**Comment by codecircuit** [comment]
I just had a short look. I will also do an update of the cuda-api-wrappers in my code during the next days.

- Minor: is the forward declaration [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/src/cuda/api/memory.hpp#L54) necessary?
- Host Prefetch should also use a `const_region_t` [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/src/cuda/api/memory.hpp#L1411)

**Comment by eyalroz** [comment]
> I just had a short look. I will also do an update of the cuda-api-wrappers in my code during the next days.
> 
>     * Minor: is the forward declaration [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/src/cuda/api/memory.hpp#L54) necessary?

It used to be, but it no longer is. Gone now.

> 
>     * Host Prefetch should also use a `const_region_t` [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/src/cuda/api/memory.hpp#L1411)

Yes, done.

**Comment by eyalroz** [comment]
> To my mind const_cast should only be used if there is no other way, e.g. for C libraries, which only have a non-const API. How do you think about that?

The only way to avoid const_cast's with these classes is to make them not inherit each other. But that would mean even more repetition.

> Minor: Member variable here has no trailing underscore, although member variable start_ has a trailing underscore.

Indeed, need to make that consistent.

> Question: We declare a default constructor here, although the member variables are not initialized. Maybe we should add initialization for start_ and size_in_bytes in struct region_t. Alternatively, a user has to initialize a region_t with region_t r{}, but that is also not required by e.g. a span.

Well, I was getting errors when trying to use an initializer list. Don't remember exactly why that is though. Let me try that again.

**Comment by eyalroz** [comment]
Ok, I managed to switch to an initializer list, but  strangely enough, I had to use curly brackets.

**Comment by codecircuit** [comment]
An alternative design without code duplication and without `const_cast`, but with public inheritance and a base class in detail namespace, can be sth like this:

```cpp
namespace detail {
template<class T>
struct base_region_t {
	T* start_;
	size_t size_in_bytes_;

	T*& start() { return start_; }
	size_t& size() { return size_in_bytes_; }

	size_t size() const { return size_in_bytes_; }
	T* start() const { return start_; }
	T* data()  const { return start(); }
	T* get()   const { return start(); }
};

}
using region_t = detail::base_region_t<void>;
using const_region_t = detail::base_region_t<const void>;
```

direct usage of the base class in the detail namespace in user code is unintended. In the sample above a `using` is sufficient to define the `region_t` and `const_region_t`. If these classes get a more specific functionality, they can inherit from `base_region_t`.

**Comment by eyalroz** [comment]
Two issues here:

* I would have to write a ctor  to allow for implicit conversion of a non-const to a const region I suppose that's doable.
* Users which look at compiler errors and warnings would see ` detail::base_region_t<void>` and ` detail::base_region_t<void const>` as parameter types. That is not so easy to resolve and is at least annoying and possibly a bit confusing. Do you believe this is worth it in order to avoid a const_cast?

**Comment by codecircuit** [comment]
This snippet addresses the conversion from `region_t` to `const_region_t`, and the readability of compiler errors.

```cpp
namespace detail {

template <class T>
class base_region_t {
private:
    T* start_ = nullptr;
    size_t size_in_bytes_ = 0;
public:
    base_region_t() = default;
    base_region_t(T* start, size_t size_in_bytes)
	: start_(start), size_in_bytes_(size_in_bytes) {}

    T*& start() { return start_; }
    size_t& size() { return size_in_bytes_; }

    size_t size() const { return size_in_bytes_; }
    T* start() const { return start_; }
    T* data() const { return start(); }
    T* get() const { return start(); }
};

}  // namespace detail

struct region_t : public detail::base_region_t<void> {
    using base_region_t<void>::base_region_t;
};

struct const_region_t : public detail::base_region_t<const void> {
    using base_region_t<const void>::base_region_t;
    const_region_t(const region_t& r) : base_region_t(r.start(), r.size()) {}
};
```

After rereading the [C++ Core Guidelines regarding `const_cast`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const) I think it is worth getting rid of `const_cast`.

I also made the member variables private, such that no user code accesses `start_` or `size_in_bytes_` directly. This is currently possible for `region_t`, but not for `const_region_t`.

**Comment by eyalroz** [comment]
@codecircuit : I'll definitely consider this approach.

However - you wrote:

> After rereading the C++ Core Guidelines regarding const_cast I think it is worth getting rid of const_cast.

and I don't understand why you think it requires we remove the const_cast. I mean, we don't actually modify the memory at the const_cast location.

> I also made the member variables private, such that no user code accesses start_ or size_in_bytes_ directly. This is currently possible for region_t, but not for const_region_t.

That helps with consistency, but - why do you see it as important to prevent direct access to these fields important?

**Comment by eyalroz** [comment]
Another point is that this way, `cuda::memory::managed::region_t` won't inherit `cuda::memory::region_t`. Or rather, it could, but then `managed::const_region_t` would inherit `const_region_t` and I'd have some duplication. Or I would need a base inheriting the base, and then some conversion operators.

**Comment by codecircuit** [comment]
> However - you wrote:
> 
> > After rereading the C++ Core Guidelines regarding const_cast I think it is worth getting rid of const_cast.
> 
> and I don't understand why you think it requires we remove the const_cast. I mean, we don't actually modify the memory at the const_cast location.

I think so because of [this example](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const):

> Example Sometimes, you might be tempted to resort to const_cast to avoid code duplication, such as when two accessor functions that differ only in const-ness have similar implementations. For example:

It is not exactly the same case here, but the same basic idea: using `const_cast` to avoid code duplication, which is not declared as good practice in the Core Guidelines.

Moreover, the code size was reduced with your newest commit. Overall we have now better readability, no `const_cast`, and reduced code duplication :+1:.
