### ISSUE TITLE
Upping the CMake version dependency

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#251]
It's recently come to my attention that it's *exceedingly* easy to install a newer CMake version. In fact, you don't have to install anything, or build anything: The [binary packages](https://cmake.org/download/) available for all CUDA-capable platforms "just work", even with older Linux distributions/Windows versions etc - and they don't clash with whatever other version you have installed.

So - I believe it is safe to bring up the minimum required CMake version; and I mean way up: 3.17 if not later.

@codecircuit : I was hoping for your opinion on this as well...

**Comment by codecircuit** [comment]
I think one of the biggest advantages is the integration of [CUDA architectures into CMake's build system](https://cmake.org/cmake/help/git-stage/prop_tgt/CUDA_ARCHITECTURES.html) (since 3.18) and the support for `find_package(CUDAToolkit)` (since 3.17). With the latter, the `cuda-api-wrappers::nvtx` target can also export the dependency to `CUDA::nvToolsExt` correctly. So I would at least take CMake version 3.18.

**Comment by eyalroz** [comment]
@codecircuit : Already on the driver-wrappers branch... feel free to take a look.

By the way - I gave a presentation about the wrappers library a few months ago, and the recording is on Youtube apparently... [here](https://www.youtube.com/watch?v=aY3iD0dzsiw). So if you want to introduce someone else to the library, that's available.

**Comment by eyalroz** [comment]
So, there's a (minor) problem. CMake's CUDA architecture detection scriptage is kind of busted with 3.19, and pribably also with 3.18; see:

https://gitlab.kitware.com/cmake/cmake/-/issues/22378

it's fine with CUDA 10 and later (I think), but it still gives me a bit of pause. On the other hand, one doesn't need it to _use_ the library, only to build the example programs, so maybe we can ignore this fact.

**Comment by eyalroz** [comment]
It seems like I'm going to settle on 3.17. The `development` branch clears Travis CI now, with it.
