### ISSUE TITLE
Correct link to `CUDA::nvToolsExt` of target `nvtx`

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#267]
We should link to the CUDA nvtx library [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/CMakeLists.txt#L68). It is sufficient to change this line to
```
target_link_libraries(nvtx PRIVATE Threads::Threads CUDA::nvToolsExt)
```

**Comment by eyalroz** [comment]
Well, CUDA::nvToolsExt should be a public dependency, shouldn't it?

And, come to think of it... shouldn't the threads dependency be public too?

**Comment by codecircuit** [comment]
It should not be `PUBLIC` because the header `nvtx/profiling.hpp`, which defines the `INTERFACE` of target `cuda-api-wrappers::nvtx` does not include any header of `Threads::Threads` or `CUDA::nvToolsExt`. If a target is linked to `cuda-api-wrappers::nvtx` the libraries of `Threads::Threads` and `CUDA::nvToolsExt` are added at the linking stage, which is sufficient.

**Comment by eyalroz** [comment]
> . If a target is linked to cuda-api-wrappers::nvtx the libraries of Threads::Threads and CUDA::nvToolsExt are added at the linking stage, which is sufficient.

But for them to be added, shouldn't the dependency be PUBLIC? Otherwise, I'm misinterpreting PRIVATE and PUBLIC.

**Comment by codecircuit** [comment]
[This post](https://cmake.org/pipermail/cmake/2016-May/063400.html) explains it pretty well.
