### ISSUE TITLE
Export dependency to CUDAToolkit

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#268]
We just need to add a line [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/cmake/cuda-api-wrappers-config.cmake.in#L7):

```
find_dependency(CUDAToolkit)
```

**Comment by eyalroz** [comment]
But we have that on the development branch...

https://github.com/eyalroz/cuda-api-wrappers/blob/development/CMakeLists.txt#L27
