### ISSUE TITLE
Build Issues with Examples

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#270]
Tested with: 46f3842cfd317b0447cd012fd671d358edf07e83 on Visual Studio 2019 using CUDA 11.5.

When I try to build the examples, I'm met with build errors like the following:

```
14>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.5.targets(731,9): Error MSB5016: The name ""arch" contains an invalid character """.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.5.targets
14>------- Finished building project: stream_management. Succeeded: False. Errors: 1. Warnings: 0
```

Is this related to the version of Visual Studio I'm using?

**Comment by eyalroz** [comment]
@DeveloperPaul123  I really hope it isn't... :-(

Don't you get any additional messages? Can you build in a more verbose way (like cmake `VERBOSE=yes`)? I think if you use `cmake --build` there's some option to make things more verbose.

**Comment by eyalroz** [comment]
Also, _I_ am getting an error on Windows, about nvToolsExt not being found. Are you getting the same thing?

**Comment by DeveloperPaul123** [comment]
No I wasn't getting that error. Not with my setup at least. I assume you're working off of `develop` right?

**Comment by DeveloperPaul123** [comment]
Changing build verbosity didn't provide me more information. I did however check the command line arguments in the visual studio project and it seems there is an extraneous character being added somewhere in CMake I would venture to guess since that is what I used to build the project. See the screenshot below under `Additional Options`:

![image](https://user-images.githubusercontent.com/6591180/141210594-b146666d-43de-42df-bfdf-cca95b759029.png)

**Comment by eyalroz** [comment]
@DeveloperPaul123 : Where is that "AdditionalOptions" being used?

**Comment by DeveloperPaul123** [comment]
They're being set by `CMakeLists.txt` 

Probably somewhere in the `examples/CMakeLists.txt`

```cmake
if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.18)
	cmake_policy(SET CMP0104 OLD)
endif()
if((NOT DEFINED CUDA_ARCH_FLAGS) OR ("${CUDA_ARCH_FLAGS}" STREQUAL ""))
	cuda_select_nvcc_arch_flags(CUDA_ARCH_FLAGS_1 Auto)
	set(CUDA_ARCH_FLAGS ${CUDA_ARCH_FLAGS} CACHE STRING "CUDA -gencode parameters")
	string(REPLACE ";" " " CUDA_ARCH_FLAGS_STR "${CUDA_ARCH_FLAGS}")
else()
	set(CUDA_ARCH_FLAGS_STR "${CUDA_ARCH_FLAGS}")
endif()
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} ${CUDA_ARCH_FLAGS_STR}")
```

**Comment by DeveloperPaul123** [comment]
Actually, I fixed it by deleting the `CMAKE_ARCH_FLAGS` in my `CMakeCache.txt`. All the samples built successfully!
