### ISSUE TITLE
Possible Improper Use of Lock Guard

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#271]
In `profiling.cpp`, the `lock_guard` variables are not named. My understanding is that this means they will be destroyed immediately which is probably not the intention for the RAII objects. 

Example:

```cpp
void point(const ::std::string& description, color_t color)
{
	::std::lock_guard<::std::mutex> { detail_::profiler_mutex };
	// logging?
	nvtxEventAttributes_t eventAttrib = {0};
	eventAttrib.version = NVTX_VERSION;
	eventAttrib.size = NVTX_EVENT_ATTRIB_STRUCT_SIZE;
	eventAttrib.colorType = NVTX_COLOR_ARGB;
	eventAttrib.color = color;
	eventAttrib.messageType = NVTX_MESSAGE_TYPE_ASCII;
	eventAttrib.message.ascii = description.c_str();
	nvtxMarkEx(&eventAttrib);
}
```

This was caught by a [clang warning](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-unused-raii.html).

**Comment by eyalroz** [comment]
> My understanding is that this means they will be destroyed immediately

Are you sure? ... hmm, that clang warning seems to suggest that might be the case. Weird.
