### ISSUE TITLE
Build fails in MS Visual Studio due to narrowing conversion

### ISSUE THREAD

**Issue by vic4key** [eyalroz/cuda-api-wrappers#295]
Hi,

I'm using Visual Studio 2019 to build the `cuda-api-wrappers` project that generated by CMake with default settings (just add an option to include `examples`) but build failed. The error comes from the function `cuda.detail_.min_grid_params_for_max_occupancy(...)` in file `multi_wrapper_impls.hpp` file. I attached a screenshot as the below. I tested all configurations that included `32-bit, 64-bit, debug, release` and none one succeeds. How can we fix it?

Thanks,
Vic P.

![Snipaste_2022-01-18_16-12-18](https://user-images.githubusercontent.com/5672864/149906704-f35319c5-f342-4ae2-a4e1-7ebcd7e97e8e.png)

**Comment by eyalroz** [comment]
Will give it a look today or tomorrow. For now, what happens if you change the code on that line to explicitly cast the int's into the other types, correspondingly?

**Comment by vic4key** [comment]
I changed the code on that line from `{ min_grid_size_in_blocks, block_size }` to `{ grid::dimensions_t(min_grid_size_in_blocks), grid::block_dimensions_t(block_size) }` then build succeed. But is that code acceptable?

**Comment by eyalroz** [comment]
It is, and has, in fact, been checked in..

**Comment by eyalroz** [comment]
Would you mind trying some of the example programs, checking whether they build and run?

**Comment by vic4key** [comment]
Yes. I willingly. For quickly, we can contact via skype:vic4key or any way.

**Comment by vic4key** [comment]
I already tried your commit. It's building successfully for all configurations.

**Comment by eyalroz** [comment]
Hmm... does CUDA even support 32-bit Windows, officially?

I was hoping GitHub actions with Windows VMs would check all of these things for me, but it always fails before actually building anything because of some CUDA configuration issue.

**Comment by eyalroz** [comment]
Can't be closed until the fix lands on the master branch.
