### ISSUE TITLE
Any plan to support vcpkg?

### ISSUE THREAD

**Issue by eladmaimoni** [eyalroz/cuda-api-wrappers#297]
I've been using vcpkg lately and found it to be very productive. I didn't see a port for cuda-api-wrappers.

Is there a plan to support this in the near future?
What is the recommended way to integrate this api into existing projects?

**Comment by eyalroz** [comment]
@elad8a : TBH, I don't have experience with vcpkg. But I would consider PR with vcpk support.

**Comment by eyalroz** [comment]
@elad8a : Ping.

Anyway, the recommended way to integrate this is:

1. Download a release tarball.
2. Decompress.
3.  `cd cuda-api-wrappers`
4.  `cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/cuda-api-wrappers` (or wherever you want it)
5. `cmake --build build`
6. `cmake --install build`

and then at the install location you have include files, library files, and CMake package configuration files.

**Comment by eyalroz** [comment]
Feel free to reopen if you have a PR.

**Comment by eladm-ultrawis** [comment]
@eyalroz Hi!

Just came back to this issue.

I made a preliminary attempt to create a vcpkg port for this library. It's basically 2 commits in my vcpkg fork [here](https://github.com/Ultrawis/vcpkg/tree/eladm/cuda-api-wrappers):

If I am not mistaken, the [contributing guide](https://github.com/microsoft/vcpkg/blob/master/CONTRIBUTING.md) for vcpkg says you need to sign a CLA. 

Let me me know if we can proceed with this.

**Comment by eyalroz** [comment]
@eladm-ultrawis : As I'm not a vcpkg user, I will need some more explanation.

The files you added seem not to fit as a part of the repository itself, but rather to refer to it:

* `versions/c-/cuda-api-wrappers.json` - seems to be one of several JSON files, having hashed the packaged repository or its files.
* `ports/cuda-api-wrappers/portfile.cmake` - seems to describe how to get the repository from GitHub and build it.

Should this really be in the repository, or in some other, VCPKG-related, repository referring to many libraries' independent repos? I'm looking for such files in libraries such as spdlog, Boost and cxxopts, and not finding any. Is it common to include them?

Also, in Martin Moene's nonstd_lite, we have [this directory](https://github.com/martinmoene/nonstd-lite/tree/master/_vcpkg/ports/nonstd-lite), apparently with the same purpose, but being a lot less verbose, without any hashes etc. Is something like that not good enough?

**Comment by eyalroz** [comment]
Also note that I have a problem with the setting up the Windows testing environment here on GitHub, due to a [CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/22893) with locating NVTX.

**Comment by eladm-ultrawis** [comment]
@eyalroz vcpkg way of working is quite complicated. But it is basically a repository of recipes that instruct vcpkg how to download and compile your library to a certain target "triplet" (architecture-compiler-os). 

To add a library to vcpkg, you need to do a PR to the vcpkg repository with the added recipe (AKA "port"). You don't need to add anything to your library (unless you use vcpkg yourself).

The new portfile (located in port directory) is basically the recipe. It tells vcpkg to download the sources from github and do a cmake install (the triplet configures the right cmake stuff such as compiler and generator).

The stuff inside "version" is autogenerated by the vcpkg executable once you correctly write the "port".

**Comment by eladm-ultrawis** [comment]
> Also note that I have a problem with the setting up the Windows testing environment here on GitHub, due to a [CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/22893) with locating NVTX.

I never submitted a PR to vcpkg, so we will have to see about this one. I am currently testing my new vcpkg port on my local windows environment with cuda 12.1.

**Comment by eyalroz** [comment]
> To add a library to vcpkg, you need to do a PR to the vcpkg repository with the added recipe (AKA "port"). You don't need to add anything to your library (unless you use vcpkg yourself).

Oh, well, in that case - you have my blessing to submit a PR that works to the VCPKG repository... :-)

**Comment by eladm-ultrawis** [comment]
@eyalroz indeed trying to link cuda-api-wrappers::nvtx fails on windows. However since this is a header only library I hope this won't be an issue with cmake.

In recent cuda versions there is the CUDA::nvtx3 target that seems to work fine. could using it serve as a workaround on windows?

**Comment by eyalroz** [comment]
It won't be an issue if you don't compile the examples; but the dependency will need to be met when the library is used.

As for nvtx3 ... hmm. Yes, that's new in CMake 3.25. Let's see if it does the trick.

**Comment by eyalroz** [comment]
Well, I resolved the NVTX problems - sort of - with issue  #490 . Closing this one, feel free to let me know if this makes it into vcpkg.

I should also note I've a bit of Windows-compatibility-related work in recent days.
