### ISSUE TITLE
Move wrap() methods for significant wrapper classes out of `detail_::`

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#298]
I might not found it, but there seems no way to construct a non-owning `cuda::stream_t`  object from a native `cudaStream_t` **without** using a function from the `detail_` namespace. I think this would be useful to improve the interoperability with other libraries. We could add a usage example in [stream_management.cu](https://github.com/eyalroz/cuda-api-wrappers/blob/master/examples/by_runtime_api_module/stream_management.cu).

**Comment by eyalroz** [comment]
The relevant function is, indeed, in the `detail_::` namespace: [`cuda::stream::detail_::wrap()`](https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/stream.hpp#L160). We also have `cuda::event::detail_::wrap()`. Do you think the `wrap()` functions should be outside the `detail_` namespace?

**Comment by codecircuit** [comment]
> Every function in a detail namespace is not part of the exposed library interface and usage outside of the library is discouraged.

I do not have a reference for that, but intuitively this is what I expect from a detail/internal namespace. This enables also changes within the detail namespace of the library without breaking user code.

**Comment by eyalroz** [comment]
@codecircuit : Well, if you interact with CUDA through the wrappers, you won't need to wrap any handles. But it's true that if you mix API wrappers code with other CUDA-related code, then you might. So I guess I can take the `wrap()` out of `detail_`.

**Comment by eyalroz** [comment]
@codecircuit : Please give [v0.4.5-rc2](https://github.com/eyalroz/cuda-api-wrappers/releases/tag/v0.4.5-rc2) a spin...

**Comment by eyalroz** [comment]
Wait a minute though.

Do you think that the function for wrapping a stream handle should be all-low-level? i.e. take the device handle? Or should it take a device_t? And similarly, when wrapping something with more context, e.g. both a CUDA device, and a CUDA context for a driver-API stream - should I also take the lower-level handles or the device_t and the context_t? In the non-`detail_` function I mean?
