### ISSUE TITLE
Device arrays with static storage duration

### ISSUE THREAD

**Issue by lahwaacz** [eyalroz/cuda-api-wrappers#30]
First, I want to say that this is an excellent and extremely useful project as it is, so this issue is not to question the design decisions or something like that, but to point out a potential caveat and maybe start a discussion about the best solution.

Let's say there is an algorithm which requires a temporary array on the device for storing  the intermediate results. One practical example is the parallel reduction, which needs an array of the length equal to the number of CUDA blocks launched. A common optimization for repeated launch of such algorithms is to avoid the allocation and deallocation by declaring the array with [static storage duration](https://en.wikipedia.org/wiki/C%2B%2B#Static_storage_duration_objects) and reallocating it only when a larger size is necessary. In practice that means either creating a global variable or declaring the local variable with `static`.

OK, let's create the problem. The [vectorAdd.cu](https://github.com/eyalroz/cuda-api-wrappers/blob/master/examples/modified_cuda_samples/vectorAdd/vectorAdd.cu) example could be modified to make the `d_A` array a global variable:
```cpp
cuda::memory::device::unique_ptr<float[]> d_A;

int main(void)
{
        ...
	auto current_device = cuda::device::current::get();
	d_A = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_B = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_C = cuda::memory::device::make_unique<float[]>(current_device, numElements);
        ...
}
```
When I compile it an run the program, it fails at shutdown:
```
[Vector addition of 50000 elements]
CUDA kernel launch with 196 blocks of 256 threads
Test PASSED
SUCCESS
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Freeing device memory at 0x0x0500960000: driver shutting down
Aborted (core dumped)
```
This can be explained with the [unspecified initialization order of global objects](https://stackoverflow.com/questions/2165223/c-controlling-destructor-order-for-global-objects) and since the destructors are called in reversed order, something in the CUDA library is apparently destructed before `cudaFree` is called from the `d_A`'s destructor.

But we can control the order of initialization by using `static` variables declared at the block level. This is where it gets interesting, because we don't know on which part of the CUDA library the `d_A`'s destructor depends. So if I write just
```cpp
int main(void)
{
	...
	auto current_device = cuda::device::current::get();
	static auto d_A = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_B = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_C = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	...
}
```
then it works as expected (at least on my system). But if I write
```cpp
int main(void)
{
	static cuda::memory::device::unique_ptr<float[]> d_A;
	...
	auto current_device = cuda::device::current::get();
	d_A = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_B = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_C = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	...
}
```
or even
```cpp
int main(void)
{
	...
	auto current_device = cuda::device::current::get();
	static cuda::memory::device::unique_ptr<float[]> d_A;
	d_A = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_B = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	auto d_C = cuda::memory::device::make_unique<float[]>(current_device, numElements);
	...
}
```
then it fails the same way as in the first case.

This apparently puts considerable constraints on writing nice, portable and efficient C++/CUDA code, if we'd like to use static storage variables for optimizations or something else. Compared to the C way of doing things, one would have to manually call `cudaFree` to deallocate the global array at the end of `main()` (or inside `my_lib_deinit()` which would have to be called at the end of `main()`). Not that I find it appealing, but it's a working approach and I even think that remembering to call `cudaFree` is easier than declaring `static` variables at the right place (if there is actually a right place for the practical case). So unless I'm missing something, I think this means that C++ idioms don't fully replace the whole spectrum of C and therefore C++ wrappers for C libraries may be inherently imperfect, although they may still be very useful for the 99% cases.

**Comment by eyalroz** [comment]
First, thank you for taking the interest in this project, and for taking the time to write this up.

About your suggestion:

I believe you're mis-generalizing from the case of some function having a static local variable it keeps over multiple runs.

First, we're talking about memory that is dynamically allocated: Not the memory for the `unique_ptr<>`, but the memory on the device. And, in fact and as you have also pointed it out, it might need to be re-allocated during the run of the program. For this reason, it does not make sense to simply "stick" a `unique_ptr<>` in the global context - both my kinds of `unique_ptr<>` and the usual C++ ones (and that's regardless of whether static initialization fails or not).

Also, making it global is not a reasonable choice, since only a single function or a few functions, involving the specific kernel you need that buffer for, need to be aware of it.

What you could do is simply make the construction lazy, e.g. using a global function:

```
template <typename T>
T* get_reduction_scratch_buffer(cuda::device::id_t device_id size_t min_size) {
    static std::optional<std::span<T>> scratch_buffer { std::nullopt };
    if (scratch_buffer.has_value() {
        auto& scratch_buffer_v = scratch_buffer.get();
        if (scratch_buffer_v.size() < min_size) {
            cuda::memory::device::free(scratch_buffer_v.data());
        }
    }
    if (not scratch_buffer.has_value() {
        scratch_buffer = { cuda::memory::device::allocate(device_id, min_size), min_size };
    }
    return scratch_buffer_v.data();
}
```
(and this could be, say, a static function in the implementation for a reduction kernel.)

Now, if you want to also be able to completely deallocate that buffer, then move from a static to a global in an appropriate namespace (again possibly within an implementation file for your reduction), and have two functions, for (re)allocating it and for deleting it - but you will want to call the explicitly. Another option is making a `lazy_unique_ptr<>` class which only gets initialized on the call, and scoping it to the part of your program which may perform reductions.

So, in a sentence: `unique_ptr<>` is not the right tool for the job. But remember you can use the simpler wrappers for allocation and de-allocation to devise your own higher-level abstraction.

**Comment by lahwaacz** [comment]
In the post above I was trying to simplify the code as much as possible to illustrate the problem, of course it is not practical anymore but the problem is still the same. In practice the we wrap the dynamic device array in a class following the [singleton pattern](https://stackoverflow.com/questions/1008019/c-singleton-design-pattern), which we believe is the right tool for it. The buffer is allocated in bytes and the singleton class provides a method to cast the data to any type, so it is usable by any instance of the function template for the reduction operation.

I don't think it is necessary to tie the problem to a specific wrapper, but if it helps, let's consider the following example of the singleton wrapper, simplified as much as possible:
```cpp
#include "cuda/api_wrappers.h"

class Singleton
{
        float* data;
        std::size_t size;

        Singleton() : data(nullptr), size(0) {}

    public:
        static Singleton& getInstance()
        {
            static Singleton instance;
            return instance;
        }

        Singleton(Singleton const&) = delete;
        void operator=(Singleton const&) = delete;

        std::size_t get_size() const
        {
            return size;
        }

        void allocate(cuda::device::id_t device_id, std::size_t new_size)
        {
            if (size < new_size)
                cuda::memory::device::free(data);
            data = (float*) cuda::memory::device::allocate(device_id, new_size);
            size = new_size;
        }

        ~Singleton()
        {
            if (data)
                cuda::memory::device::free(data);
        }
};

int main(void)
{
    auto current_device = cuda::device::current::get();
    Singleton& s = Singleton::getInstance();
    if (s.get_size() == 0)
        s.allocate(current_device.id(), 100);
    return 0;
}
```
If you compile it and run the program, it will fail with `cuda::runtime_error` for exactly the same reason as I was trying to explain above: the singleton is initialized on the stack before the dynamic allocation happens and thus before the CUDA driver gets initialized (I think this because the error message says `Freeing device memory at 0x0x0500960000: driver shutting down`). And since the static things get destroyed in reversed order, the driver shuts down before our destructor calls `cudaFree`.

Obviously it is easy to reorder the practical code in such a way that some relevant part of the CUDA API is used before the singleton, but it is even easier to forget about it and we don't even know which parts of CUDA might affect this (notice that the `cuda::device::current::get()` call before the singleton initialization was OK).

(By the way, what is `std::span` and `lazy_unique_ptr<>` in your code above? I can't find them anywhere in the STL or this project.)

**Comment by eyalroz** [comment]
Before replying to the main part of your comment: `lazy_unique_ptr<>` - just came up with it. Essentially it would be like a `unique_ptr<>` but would not allocate until you try to `get()` from it, similarly to the function I suggested (but without the reallocation-by-size functinality).

As for `std::span` - that will probably happen in C++20, I was getting ahead of myself. I meant the GSL span, see [this introduction](https://stackoverflow.com/questions/45723819/what-is-a-span-and-when-should-i-use-one/45723820) to spans.

**Comment by eyalroz** [comment]
As for the main part: Your class doesn't quite make sense as-is, because you have a singleton but you actually need to cater to multiple device, each of which may need a singleton. You could make a "multiton which, per-device, is a singleton" out of it though.

Now, indeed, you do get that error when trying to make any CUDA runtime API call when it's started unloading (which happens sometime after `main()` has concluded). Possible solutions/workarounds (other than simply not having static-lifetime allocations) would be:

1. Having a cross-process CUDA context (there is something like that in existence I think, but I forget the details).
2. Being able to determine if the driver is currently unloading or not (no such functionality per se right now).
3. Asking foregiveness rather than asking permission... i.e.:

       ~singleton_buffer_t()
       {
       	if (data == nullptr) { return; }
       	try { cuda::memory::device::free(data); }
       	catch(cuda::runtime_error& e) {
       		if (e.code() != cuda::status::cuda_runtime_unloading) { throw e; }
       	}
       }

**Comment by lahwaacz** [comment]
It makes sense for single-GPU systems or even for programs using only one device, the _current one_ as specified by the environment (i.e. "single device in a single process" approach). However, even if you generalize it to the "multiton", you would still get the same problem. Again, I highly doubt that you can devise a high-level wrapper to fix this problem with a very low-level language feature.

As for your first possible solution, please let me know if you come across the details of cross-process CUDA context! The third one is not really a solution: although the error is avoided and it's arguably not a memory leak since it happens in the program shutdown sequence, there is still a possible _resource_ leak because you have no idea what data are stored in the particular singleton, nor in what way it could affect the CUDA driver. Also, combined with the cross-process CUDA context, there might actually be a memory leak. And the second option would not really acomplish anything, except simplifying option 3.

I've actually found a way around the problem by registering the singleton's destructor-like method with `atexit`. At least on Linux, the `atexit`-registered functions seem to run before the CUDA driver gets unloaded, but I doubt that it's portable.

**Comment by eyalroz** [comment]
About the first possible solution: I mean a single-process context which other processes use through inter-process communications.

About the third solution: I don't quite follow your objection. While your singleton is in in scope, it has a `cudaMalloc()`'ed, and when it goes out of scope it ceases to have it - as, if the CUDA runtime is unloading, all allocations have been invalidated (and the behavior is indistinguishable from the `cudaFree()` having succeeded just before the runtime beginning to unload). Correct me if I'm wrong.
