### ISSUE TITLE
`make_unique` without device behaves strangely in the example `vectorAdd`

### ISSUE THREAD

**Issue by QuarticCat** [eyalroz/cuda-api-wrappers#327]
My environment is

- GCC 12.1.0
- CMake 3.23.1
- CUDA 11.6
- cuda-api-wrappers latest commit
- RTX 2070 Super
- Linux 5.17.9

In the example [vectorAdd](https://github.com/eyalroz/cuda-api-wrappers/blob/master/examples/modified_cuda_samples/vectorAdd/vectorAdd.cu), if I change

```cpp
auto device = cuda::device::current::get();
auto d_A = cuda::memory::device::make_unique<float[]>(device, numElements);
auto d_B = cuda::memory::device::make_unique<float[]>(device, numElements);
auto d_C = cuda::memory::device::make_unique<float[]>(device, numElements);
```

to

```cpp
auto d_A = cuda::memory::device::make_unique<float[]>(numElements);
auto d_B = cuda::memory::device::make_unique<float[]>(numElements);
auto d_C = cuda::memory::device::make_unique<float[]>(numElements);
```

I will get

```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Failed releasing the reference to the primary context for device 0: invalid device context
```

Sometimes I get a SIGSEGV.

I thought these two code pieces are equivalent.

**Comment by eyalroz** [comment]
This is due to premature destruction of the primary context of the device. I'm working on it, but it's not just a local typo, so this will take a bit of time.

**Comment by QuarticCat** [comment]
@eyalroz I still got a SIGSEGV. I'm sure that I have already switched to the development branch. The SIGSEGV happened in the first `cuda::memory::copy` call. The addresses of `d_A`, `d_B`, and `d_C` are `0x00007fd300bb8f00`, `0xa08fc50ed476ac00`, `0x00007fd300bb8e20`, respectively in one execution.

**Comment by eyalroz** [comment]
> I'm sure that I have already switched to the development branch.

And you `git pull`'ed to make sure you have the HEAD?

> The SIGSEGV happened in the first `cuda::memory::copy` call. 

And the only change you made was in the `make_unique`, right?

**Comment by QuarticCat** [comment]
> And you `git pull`'ed to make sure you have the HEAD?

Yes. And I also checked that the installed lib contains the modified code you just committed.

```console
> git log -n 1
commit 94813e909fcd5471f94248d734597bbcdfb5cd25 (HEAD -> development, origin/development)
...
```

> And the only change you made was in the `make_unique`, right?

I also removed the first line `#include "../../common.hpp"` but I think that doesn't matter.

**Comment by eyalroz** [comment]
Yeah, can reproduce it now. So, another mysterious issue left to investigate other than what I thought would resolve this...

**Comment by QuarticCat** [comment]
Now it works. :tada:

**Comment by eyalroz** [comment]
I absolutely don't understand why my compiler did not complain about not returning a value from a non-void function :-(

**Comment by QuarticCat** [comment]
> I absolutely don't understand why my compiler did not complain about not returning a value from a non-void function :-(

I actually explored this problem a bit yesterday. It seems that nvcc can report this warning if you copy the implementation of `make_unique` to your code. The reason why it doesn't may be that CMake uses `-isystem` to include your library instead of `-I`, see https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers?noredirect=1&lq=1. Maybe you should find a way to overwrite this behavior for your example builds. Like, directly uses `target_include_directories`? I'm not sure.

**Comment by eyalroz** [comment]
> CMake uses -isystem to include your library instead of -I, 

Really? I get:
```
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler  -I/home/eyalroz/src/mine/cuda-api-wrappers/src -isystem=/usr/local/cuda/include -O3 -DNDEBUG --generate-code=arch=compute_61,code=[compute_61,sm_61] --compiler-options=-Wall --compiler-options=-Wextra --compiler-options=-Wno-missing-field-initializers -std=c++11 -MD -MT examples/CMakeFiles/event_management.dir/by_runtime_api_module/event_management.cu.o -MF CMakeFiles/event_management.dir/by_runtime_api_module/event_management.cu.o.d -x cu -c /home/eyalroz/src/mine/cuda-api-wrappers/examples/by_runtime_api_module/event_management.cu -o CMakeFiles/event_management.dir/by_runtime_api_module/event_management.cu.o
/usr/bin/c++ -O3 -DNDEBUG CMakeFiles/context_management.dir/by_driver_api_module/context_management.cpp.o -o bin/context_management  /usr/local/cuda/lib64/libcudart.so /usr/lib/x86_64-linux-gnu/libcuda.so 
```
... for example

**Comment by QuarticCat** [comment]
Then it should report a warning. I've tested this by manually invoking nvcc in command line.

This is how I include your lib:

```console
$ git clone https://github.com/eyalroz/cuda-api-wrappers
$ cd cuda-api-wrappers
$ cmake -B build -DCMAKE_INSTALL_PREFIX=./cuda-api-wrappers
$ cmake --install build
$ mv cuda-api-wrappers path/to/my-project/third_party
```

**Comment by QuarticCat** [comment]
By my tests, nvcc can report `-Wreturn-type` warning even without `-Xcompile -Wall`. You can confirm this by removing the `return` and then execute

```console
$ nvcc -forward-unknown-to-host-compiler -I/path/to/my-project/third_party/cuda-api-wrappers/include -isystem=/opt/cuda/include -g --generate-code='arch=compute_52,code=[compute_52,sm_52]' -std=c++14 -c /path/to/my-project/main.cu
```

**Comment by eyalroz** [comment]
Somehow I'm seeing the warning now. Weird.

**Comment by QuarticCat** [comment]
Consider deleting the build directory and build again as some of your previous CMakeLIsts.txt modifications may be cached.

**Comment by QuarticCat** [comment]
In fact I had just learned CUDA for less than a week and am looking for a practice project. :rofl:
