### ISSUE TITLE
Library does not apply MSVC __cplusplus workaround consistently

### ISSUE THREAD

**Issue by Q-Minh** [eyalroz/cuda-api-wrappers#337]
Hi, thanks for this library, I am really looking forward to using it. 
I've had some problems compiling most of the example programs using Visual Studio 2019, CMake 3.18.4, and CUDA 11.4.

I've tried building the `vectorAdd_profiled`, `array_management` and `device_management` targets for example, which all fail on my setup. 
First, the `nvtx.hpp`, `nvrtc.hpp` and `api.hpp` all have the guard 
```
static_assert(__cplusplus >= 201103L, "The CUDA NVTX API wrappers can only be compiled with C++11 or a later version of the C++ language standard");
```
which cause compilation to fail, since I am using MSVC without the `/Zc:__cplusplus` option, causing `__cplusplus` to indicate the incorrect C++98 standard is being used.

I've thus replaced these with
```
#if (__cplusplus < 201103L && (!defined(_MSVC_LANG) || _MSVC_LANG < 201103L))
#error "The CUDA Runtime API headers can only be compiled with C++11 or a later version of the C++ language standard"
#endif
```
similarly to [this commit](https://github.com/eyalroz/cuda-api-wrappers/commit/51447b7a70f9f22252e27eac1cf33925bbfb7e04). 

Then, another compilation error is related to the fact that `HANDLE` is undefined, specifically in `cuda/api/virtual_memory.hpp`. So, as a quick and dirty fix, I've added an `#include <windows.h>` to `virtual_memory.hpp` to define `HANDLE`. Now,  `array_management` compiles, but not `device_management`, because of the use of `std::numeric_limits<int>::max()`. Because of the `#include <windows.h>`, the expression `max` is actually a macro and gets string-replaced by the preprocessor in std::numeric_limits<int>::max()` causing compilation to fail.

Instead of digging deeper, I wanted to seek your help on how to make your library usable on my system, if possible. 
Are there specific pointers on to how to use this library on Windows with CMake and Visual Studio 2019? I've successfully compiled all the samples from the CUDA Toolkit v11.4 with VS2019, so I know I have a CUDA 11.4 capable environment.

**Comment by eyalroz** [comment]
> since I am using MSVC without the /Zc:__cplusplus option,

Shouldn't you just be passing `/std:c++11`, or `/std:c++14` etc?

**Comment by Q-Minh** [comment]
- The `/std:c++xx` do not affect the `__cplusplus` macro if the `/Zc:__cplusplus` option is not specified.
- I'm trying to build the examples from the `cuda-api-wrappers` repo itself, not using the library from my own code currently. I'm basically just running 
  ```
  cmake -S . -B build -DBUILD_EXAMPLES=ON
  cmake --build build --target device_management --config Release
  ```

**Comment by eyalroz** [comment]
So, I'm angry that CMake doesn't solve this magically... added a comment [here](https://gitlab.kitware.com/cmake/cmake/-/issues/18837). I'll change the static assert like you suggest, basically; but please open a different bug for the other issue.

**Comment by Q-Minh** [comment]
See separate issue #338

**Comment by eyalroz** [comment]
So, apparently I had already solved this in the preprocessor check in `types.hpp`, but then forgot about it when I added `static_assert()` to the top-level header files (`api.hpp`, `nvrtc.hpp`, `nvtx.hpp`). Also, will unify the error message for all of these.

**Comment by eyalroz** [comment]
Also... one of the reasons this regression slipped by me is that, somehow, I couldn't get the GitHub CI machines to properly download and install CUDA - although when I do the same thing manually it seems to work. If you happen to have any experience with this sort of thing, [this is the Powershell install script](https://github.com/eyalroz/cuda-api-wrappers/blob/development/.github/action-scripts/install-cuda-windows.ps1).

**Comment by Q-Minh** [comment]
> Also... one of the reasons this regression slipped by me is that, somehow, I couldn't get the GitHub CI machines to properly download and install CUDA - although when I do the same thing manually it seems to work. If you happen to have any experience with this sort of thing, [this is the Powershell install script](https://github.com/eyalroz/cuda-api-wrappers/blob/development/.github/action-scripts/install-cuda-windows.ps1).

I've had some experience with GitHub Actions a couple of years back, but nothing related to GPUs. I'm quite busy at the moment, but if this still isn't resolved in a couple of months, I will gladly take a look into this.
