### ISSUE TITLE
std:: -> ::std::

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#347]
When compiling with CUDA 11.7, we need to use `::std::`, not `std::`, to avoid CUDA's not-quite-standard library.

**Comment by nenomius** [comment]
https://github.com/eyalroz/cuda-api-wrappers/blob/fb5a9a67a9f930a2d20620e0b7fdf0ccdc5ea572/src/cuda/api/multi_wrapper_impls/kernel_launch.hpp#L172

**Comment by eyalroz** [comment]
@nenomius : Whoops... :-( Thank you.
