### ISSUE TITLE
Support for cooperative kernel launches

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#35]
I think this can be achieved by adding

```cpp
template<typename KernelFunction, typename... KernelParameters>
inline void launch_cooperative(
	const KernelFunction&       kernel_function,
	launch_configuration_t      launch_configuration,
	void**                      args)
{
	cudaLaunchCooperativeKernel(
		kernel_function.ptr(),
		launch_configuration.grid_dimensions,
		launch_configuration.block_dimensions,
		args,
		launch_configuration.dynamic_shared_memory_size
	);
}
```

in `kernel_launch.cuh`.

**Comment by eyalroz** [comment]
Yes, this is new with CUDA 9... what a headache. It's more than just this individual function - all launches may now be cooperative.

I wonder... what do you think? Should we just put a cooperative/non-cooperative flag in the launch parameters?

**Comment by eyalroz** [comment]
Also, I willl want an API without the silly void** array. That's _way_ to C-like. Some variadic template magic can probably allow us to write a nice wrapper.

**Comment by lahwaacz** [comment]
@codecircuit Your function is missing the stream configuration.

@eyalroz You will also probably want to plan this along with [cudaLaunchCooperativeKernelMultiDevice](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#multi-device-synchronization-cg).

**Comment by eyalroz** [comment]
@lahwaacz : One headache at a time...

First, please have a look at my new branch.

**Comment by eyalroz** [comment]
@codecircuit : ping.

**Comment by codecircuit** [comment]
64 bytes from codecircuit ...

@eyalroz Thx for the fast implementation. It looks good.
@lahwaacz with `cudaLaunchCooperativeKernelMultiDevice` it should be more difficult, as that function requires e.g. a `CUfunction`, which can be obtained in the CUDA Driver API. Or is there a mechanism to 'convert' a in-source kernel into a `CUfunction`?

**Comment by eyalroz** [comment]
Fixed by commit 3c1b5f40e73f8892e9f07394e7773d6e526ad9e0.

**Comment by eyalroz** [comment]
Well, at least the single-device version.

**Comment by eyalroz** [comment]
@codecircuit noticed there are compilation issues with the execution control example program as I've committed it. Reopening.
