### ISSUE TITLE
memMapIPCDrv example does not compile with MSVC C++17

### ISSUE THREAD

**Issue by Q-Minh** [eyalroz/cuda-api-wrappers#351]
As stated in the title, the example target `memMapIPCDrv` doesn't compile with VS2019. 
First problem is replacing `#eldif` with `#elif` right [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/examples/modified_cuda_samples/memMapIPCDrv/parent.cpp#L47). 
Second problem is adding an address of operator (`&`) right [here](https://github.com/eyalroz/cuda-api-wrappers/blob/development/examples/modified_cuda_samples/memMapIPCDrv/helper_multiprocess.cpp#L110) to get `&process` instead of `process` given as argument to `CreateProcess`. I'm not familiar with Windows programming, but I am basing this statement on the declaration:
```
typedef struct _PROCESS_INFORMATION {
    HANDLE hProcess;
    HANDLE hThread;
    DWORD dwProcessId;
    DWORD dwThreadId;
} PROCESS_INFORMATION, *PPROCESS_INFORMATION, *LPPROCESS_INFORMATION;
```
found in `processthreadsapi.h` file of the win api. Looks like `LPPROCESS_INFORMATION` is a pointer to `PROCESS_INFORMATION`, and the function `CreateProcess` expects an `LPPROCESS_INFORMATION`. 

With these fixes in place, compilation succeeds, but linking fails, stating `LNK1104: cannot open file 'c.lib'`. Again, not familiar with Windows programming, but it seems like [this](https://github.com/eyalroz/cuda-api-wrappers/blob/development/examples/CMakeLists.txt#L62) is the culprit. Are there such libraries named `c.lib` and `rt.lib`? I know there is something called the CRT in windows, as in the 'C Runtime', but nothing more.

**Comment by eyalroz** [comment]
So, fixed the typo. And now also the linking issue.

As for the &process - I copy-pasted this code from NVIDIA's own sample, I assumed it should work...

**Comment by eyalroz** [comment]
Marking as resolved for now - please reopen if it still doesn't work.
