### ISSUE TITLE
Grid synchronization requires relocatable device code

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#38]
The sample `execution_control` must be compiled with `nvcc` flag `-rdc=true`. Otherwise the `grid.sync()` causes a linking error for `-arch sm_60` or `-arch sm_61`. See CUDA C Programming Guide chapter C.3. Grid Synchronization.

Reproduceable by:

```
cd examples/by_runtime_api_module
nvcc -std=c++11 -I../../src -arch sm_61 execution_control.cu -o execution_control
```

Fixed by:

```
cd examples/by_runtime_api_module
nvcc -rdc=true -std=c++11 -I../../src -arch sm_61 execution_control.cu -o execution_control
```

This flag should be specified in the `CMakeLists.txt`. Is there a possibility to add
target specific compile time flags? I tried to add `target_compile_options(execution_control PUBLIC "-rdc=true")` in `CMakeLists.txt` without any effect. Adding `-rdc=true` to the general compile flags seems not to be a solution.

**Comment by lahwaacz** [comment]
Options for the `nvcc` go to the `cuda_add_executable` macro (see https://cmake.org/cmake/help/v3.9/module/FindCUDA.html):
```
CUDA_ADD_EXECUTABLE( cuda_target file0 file1 ...
                     [WIN32] [MACOSX_BUNDLE] [EXCLUDE_FROM_ALL] [OPTIONS ...] )
```

Or maybe if you upgrade to [cmake 3.10.2](https://cmake.org/cmake/help/v3.10/module/FindCUDA.html) and port everything to work with `enable_language(CUDA)`, then `target_compile_options` might work...

**Comment by eyalroz** [comment]
@lahwaacz : I can't expect users of cuda-api-wrappers to have the latest CMake 3.10.2 ...

**Comment by eyalroz** [comment]
So, the thing is, I'm seeing the opposite with some older uarchictectures, i.e. -rdc messes up the linking somehow. Will look further into this tomorrow probably

**Comment by codecircuit** [comment]
With the recent commit the following example is not executable for architectures >= sm_60
and returns the error: `invalid device function`:

```
$ cmake ..
$ make execution_control
$ ./examples/bin/execution_control
```

because the device code is still not relocatable. I checked the compile flags with `make VERBOSE=1 execution_control | grep rdc`, which returns 1. If I comment out the grid synchronization everything works fine.

**Comment by eyalroz** [comment]
@codecircuit : I _think_ this resolves things, but reopen if it doesn't.

**Comment by codecircuit** [comment]
@eyalroz: ✅ It works. Thx.

**Comment by eyalroz** [comment]
@codecircuit : Right back at you - thanks for reporting these issues and being patient with my not-always-working fixes :-)
