### ISSUE TITLE
Make the library usable with FetchContent

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#382]
I could probably make the library usable with FetchContent, so that this would work:
```
FetchContent_Declare(cuda_api_wrappers_fc
    GIT_REPOSITORY https://github.com/eyalroz/cuda-api-wrappers.git
    GIT_TAG v12.34.45 # Replace this with a real available version
)
FetchContent_MakeAvailable(cuda_api_wrappers_fc)
```

**Comment by EmmanuelMess** [comment]
Added a bounty of [u$d 5 to the issue](https://app.bountysource.com/issues/109848593-make-the-library-usable-with-fetchcontent).

**Comment by eyalroz** [comment]
Well, that was easy... the library is already usable with FetchContent. I just checked...

**Comment by EmmanuelMess** [comment]
Missing `include(FetchContent)` and the library probably doesnt need to end in `_library` at the end. And there is a `target_link_libraries(Project cuda nvrtc)`line that is still required for the build to run.

**Comment by eyalroz** [comment]
> Missing include(FetchContent) 

Yes, I'll add that.

> and the library probably doesnt need to end in _library  at the end. 

That's to avoid any potential clashes with stuff within the library; although maybe it's not 100% necessary.

> And there is a target_link_libraries(Project cuda nvrtc) line that is still required for the build to run.

No, it's not... if you `target_link_libraries(my_tgt runtime-and-driver)` (and that's all you need then it works and links against the relevant libraries.

**Comment by EmmanuelMess** [comment]
`target_link_libraries(my_tgt runtime-and-driver)` can't get this to work, it doesnt find `#include <cuda/api.hpp>` maybe its a mistake in the include path?

**Comment by eyalroz** [comment]
Really? That's weird... Anyway, I'll have another look.

**Comment by eyalroz** [comment]
So, I'm going to improve things! You will now be able to use the same namespace with find_package and with FetchContent!

**Comment by EmmanuelMess** [comment]
@eyalroz Please claim the bounty :)
