### ISSUE TITLE
overall_dimensions_t should be constructible from a dim3 struct

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#404]
While overall_dimensions_t is a 3-dimension variable, with 3 size_t's, dim3 is not - it uses unsigned ints.

We should support construction using dim3's (but not the conversion back).

**Comment by hofstee** [comment]
Shouldn't it be a `dim3&` or a `const dim3&` like the other places using a dim3 with constexpr? Otherwise with MSVC I get the following error: `a constexpr function cannot have a parameter of nonliteral type "dim3"`.

**Comment by eyalroz** [comment]
Done... @hofstee : Please have a look / give this a try.

**Comment by hofstee** [comment]
Seems to work on my end! Thanks!
