### ISSUE TITLE
Multi GPU support is broken from v0.5.4 to the current development branch

### ISSUE THREAD

**Issue by DiamonDinoia** [eyalroz/cuda-api-wrappers#418]
Hi,

The current multi GPU support does not work. It either hangs or causes a:
```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Synchronously copying data: an illegal memory access was encountered
```
It seems to me that the problem is that data is not allocated to the correct device by `cuda::memory::device::make_unique`

example here:
https://github.com/DiamonDinoia/test-cuda/tree/master/cuda-api-wrappers-multi-example

Until version 0.5.0 this worked fine. Unfortunately, I cannot use that version anymore as systems were updated to cuda 11.8 which causes the `::std` issue.

Thanks,
Marco

**Comment by eyalroz** [comment]
I can reproduce the hang, but not the error. Actually, the hang is so bad that I can't kill the process.

**Comment by eyalroz** [comment]
So, whittling down the program to see where things go wrong, it's enough - on my system - to have:
```
void vectorAddMulti(const int i) {
    cuda::context::handle_t pc_handle;
    auto status = cuDevicePrimaryCtxRetain(&pc_handle, i);
    return;
}
```
... to get the hang. 

This suggests to me that the issue may be with the interaction of OpenMP and the CUDA driver, rather than my wrappers. Can you check on your system?

**Comment by DiamonDinoia** [comment]
The previous version had the same issue with and without OpenMP.

The code above does not hang with and without OpenMP.

**Comment by eyalroz** [comment]
> The previous version had the same issue with and without OpenMP.

Can you create something which triggers the hang or the error without using OpenMP?

**Comment by eyalroz** [comment]
Oh, wait... it looks like I'm seeing a hang with _any_ program using the GPU after running test_multi once in its full version. Probably need to restartt my machine... :-(

**Comment by DiamonDinoia** [comment]
[This](https://github.com/DiamonDinoia/test-cuda/tree/master/cuda-api-wrappers-multi-example) version I posted here hangs without openmp. If you see the cmake file. OPENMP is disabled by default:
```cmake
option(ENABLE_OMP "enables omp for parallelism" OFF)
```

**Comment by eyalroz** [comment]
Ok. Now, It looks on my system the program gets stuck on the second iteration (second device), during the copy from device to host. Is that what you see as well?

**Comment by DiamonDinoia** [comment]
Yes. That's exactly what I see with that version.

**Comment by eyalroz** [comment]
Got an error once...
```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Freeing device memory at 0x07f4e0d661c00: an illegal memory access was encountered
Aborted
```
Still puzzled by this :-(

**Comment by DiamonDinoia** [comment]
Exactly. I saw this too. I think the problem is that memory is allocated on the wrong device.

**Comment by eyalroz** [comment]
@DiamonDinoia : CUDA knows which device each address corresponds to, so that should not be a problem. Also, I get the hang  when calling `cuMemCpy()`. And, honestly, that should never hang. At most it should fail and return some error code. Annoying :-(

**Comment by DiamonDinoia** [comment]
0.5.0 was the last working version

**Comment by DiamonDinoia** [comment]
Yes exactly. Hence the only place where this goes on is when  
````cpp 
auto d_B    = cuda::memory::device::make_unique<float[]>(device, numElements);
````
is called. I think that the way `device` is used allocates memory always on device 0

**Comment by eyalroz** [comment]
No, the context stack when allocating has the primary context of the device we want (I double-checked by inserting function calls to my context-stack-dumper function from `examples/common.hpp`). Also, even if that had not been the case - it's the kernel execution which should have failed, so that the `device.synchronize()` would throw an exception about an invalid memory access.

**Comment by eyalroz** [comment]
The issue is averted if you add `device.make_current()` before performing any of the work (i.e. the copies, launch, synch, copy). I don't like suggesting that, since it should really not be necessary. Would you verify?

**Comment by DiamonDinoia** [comment]
I just tried and that seems to fix the issue.

**Comment by eyalroz** [comment]
So, as far as I am concerned - this is is a bug with the driver or the NVIDIA user-space libraries; and its workaround is just being a bit careful with the setting of the current device / context.

**Comment by DiamonDinoia** [comment]
It seems that this workaround does not allow to use the GPUs in parallel. My code got slower after doing so and I discovered that the GPUs were used one after the other.

**Comment by DiamonDinoia** [comment]
Oh, it seems an OpenMP issue. The normal behaviour is restored using std::threads. I will investigate what the problem is. Likely compiler flags misplaced
