### ISSUE TITLE
Kernel gets wrong argument values

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#42]
Executing the example code in #40 results with the recent commits now into the following output:

```
Launching non-cooperative
a = 1, b = 2, c = 0
Launching cooperative
a = 3, b = -490680, c = 0
```

My environment:

- Cuda compilation tools, release 9.0, V9.0.176
- gcc 5.1.0 or gcc 6.3.0

I compiled with:

- `nvcc -std=c++11 -I cuda-api-wrappers/src test.cu -o test`
- `nvcc -std=c++14 -I cuda-api-wrappers/src test.cu -o test`

**Comment by eyalroz** [comment]
Whoops, commit typo.
