### ISSUE TITLE
Lingering `link::input_type_t` in `cuda/api/link.hpp`

### ISSUE THREAD

**Issue by jhol** [eyalroz/cuda-api-wrappers#442]
There is a lingering reference to `link::input_type_t` in `cuda/api/link.hpp` in a C++17-only section of code. This should be replaced with `link::input_kind_t`.

**Comment by eyalroz** [comment]
I should make a bugfix release soon...

**Comment by eyalroz** [comment]
Done, see:

https://github.com/eyalroz/cuda-api-wrappers/releases/tag/v0.6.1-rc1

... and don't hesitate to give any feedback.
