### ISSUE TITLE
Member initialisation order error.

### ISSUE THREAD

**Issue by j-horner-c4x** [eyalroz/cuda-api-wrappers#443]
First, thanks for putting the time into making this library.

I got an error when using `cuda::memory::device::unique_ptr<T[]>`

```
cuda\api\array.hpp(160): error : the initialization of member "cuda::array_t<T, NumDimensions>::dimensions_" will be done before that of member "cuda::array_t<T, NumDimensions>::context_handle_"
```
In version 0.6.1.

Swapping the initialisation order in the constructor to match the member list fixes the issue.

**Comment by eyalroz** [comment]
Well, that's not an error - you're not required to initialize in the same order, but - sure, it's nicer to do it in order.

**Comment by j-horner-c4x** [comment]
Yeah, I suppose it's technically a warning. But I didn't have "warnings as errors" enabled... Anyway, thanks again!

**Comment by eyalroz** [comment]
@j-horner-c4x : It may take a little time before 0.6.2 comes out with this integrated. For now you'll need to either use the development branch or reverse the order yourself.
