### ISSUE TITLE
Dependence on CUB?

### ISSUE THREAD

**Issue by makortel** [eyalroz/cuda-api-wrappers#45]
Hi,

I was trying to update our version of cuda-api-wrappers to the HEAD (fe0f79bd6ed2c25efb7b1ada19e9718f5299971e), when I stumbled on the recently-added dependence on CUB (3f165286082d6261b3dacad8a8c2c0c5dae700e8). The dependence itself is fine (even if I didn't manage to find any actual use of that in cuda-api-wrappers), my exact problem being how to build cuda-api-wrappers now. After adding CUB as a dependence of cuda-api-wrappers in our (non-CMake) build system, I get the following error from CMake when building cuda-api-wrappers
```
CMake Error at CMakeLists.txt:96 (find_package):
  By not providing "FindCUB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUB", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUB" (requested
  version 1.5.0) with any of the following names:

    CUBConfig.cmake
    cub-config.cmake

  Add the installation prefix of "CUB" to CMAKE_PREFIX_PATH or set "CUB_DIR"
  to a directory containing one of the above files.  If "CUB" provides a
  separate development package or SDK, be sure it has been installed.
```
Is the problem something that should be fixed in cuda-api-wrapper build rules, or in our build rules (I'm rather newbie concerning CMake)? (or maybe the dependence on CUB could be removed for time being if it is not really needed?)

Thanks,
Matti

**Comment by fwyzard** [comment]
#46 fixes the issue, at least in our build environment.

However now the problem is that there is no `examples/other/sort_with_cub.cu` file in the repository !

**Comment by fwyzard** [comment]
#47 is an alternate fix, reverting the introduced dependency on CUB .

**Comment by eyalroz** [comment]
I've removed the dependency on CUB for the time begin - PR #47 .
