### ISSUE TITLE
Missing definition for allocate_managed() in src/cuda/api/context.hpp

### ISSUE THREAD

**Issue by kingcrimsontianyu** [eyalroz/cuda-api-wrappers#455]
As the title states. The same issue exists for `allocate()`.

**Comment by eyalroz** [comment]
@kingcrimsontianyu : Fixed. Sorry, that one slipped by me somehow. TBH, the repository is really missing unit test coverage (and the example programs don't cover that much, see #18). But I just don't have the time to sit down and write all of that - with this being a spare-time project only.
