### ISSUE TITLE
NVTX library not found on ubuntu-17.10

### ISSUE THREAD

**Issue by erikman** [eyalroz/cuda-api-wrappers#49]
On Ubuntu-17.10 CUDA is installed directly under `/usr`, and libraries are installed alongside system libraries in `/usr/lib/x86_64-linux-gnu`.

`find_library` fails to find NVTX because `NO_DEFAULT_PATH` has been specified. Removing `NO_DEFAULT_PATH` makes detection work and library builds as expected.

I believe removing `NO_DEFAULT_PATH` should be safe because it is only used as a fallback option, but I'm not 100% sure.

**Comment by eyalroz** [comment]
For now, I don't have a better idea than what you've suggested, so you've got it.

**Comment by erikman** [comment]
thanks :)

**Comment by erikman** [comment]
I will ;) I'm creating a course in *C++ GPGPU programming with CUDA* for the company I work for, https://www.edument.se (we sell education and do consulting), so your wrappers will be mentioned as a nice way of getting RAII and other modern C++ constructs on the CUDA api.

**Comment by eyalroz** [comment]
@erikman : Can I have your email? This discussion exceeds the scope of this issue page. Or - you could email me (my email is on my profile page here).
