### ISSUE TITLE
Remove unused user-defined conversion?

### ISSUE THREAD

**Issue by billtohara** [eyalroz/cuda-api-wrappers#51]
When compiled with clang-5 and -Weverything, this rather magical function triggers a lot of warnings:

https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/device.hpp#L834

 warning: conversion function converting 'cuda::device_t<false>' to itself will never be used

Can this be written in such a way as to avoid generating the device_t<false> to device_t<false> case? This c++ is a bit advanced for me :-(

**Comment by eyalroz** [comment]
> Can this be written in such a way as to avoid generating the device_t to device_t case? 

That is actually a good question. I thought the `std::enable_if` should do the trick, but apparently it doesn't. Would you consider asking about this on StackOverflow perhaps?

**Comment by eyalroz** [comment]
Oh wait, actually I thought of something. Can you try replacing the function signature with
```
device_t<not AssumedCurrent>()
```
?

If this builds, try running all the tests. It's a slightly uglier hack than what I have now...

**Comment by billtohara** [comment]
That seems to do the trick!

**Comment by eyalroz** [comment]
No, don't close it yet, I need to commit it into the code... which I can't do for a few more days since I'm travelling.
