### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#515]
- `stream.hpp` uses `pool_t` defined in `memory_pool.hpp`
- `memory_pool.hpp` uses `ipc::ptr_handle_t` defined in `ipc.hpp`
- `nvtx/profiling.hpp` uses `scoped_existence_ensurer_t` defined in `api/multi_wrapper_impls/context.hpp`

**Comment by eyalroz** [comment]
That's what I get for not having proper unit tests for things. :-(

Will fix this tomorrow.

**Comment by eyalroz** [comment]
How about this? (development branch)

**Comment by codecircuit** [comment]
in `profiling.hpp` line 289 the full object definition of `scoped_existence_ensurer_t` is required. A forward declaration is not sufficient and results into compiler error:

```
cuda-api-wrappers/src/cuda/nvtx/profiling.hpp(289): error: incomplete type is not allowed
   context::current::detail_::scoped_existence_ensurer_t context_existence_ensurer;
```

**Comment by codecircuit** [comment]
Thanks, this fixes it.
