### ISSUE TITLE
Scheduling a memory copy on stream 0x056b5efe0: context is destroyed

### ISSUE THREAD

**Issue by thomas-bouvier** [eyalroz/cuda-api-wrappers#537]
Hello,

Thank you for this great library. I'm using it extensively at the moment.

I have a C++ application which I run using MPI, i.e., `mpiexec -np 8 -hosts ip:8 ...`. In a constructor, I have the following lines that 1) retrieve the local rank and 2) create a stream:

```cpp
m_local_rank = rank % cuda::device::count();
m_client_stream_sync = std::make_unique<cuda::stream_t>(cuda::device::get(m_local_rank).create_stream(cuda::stream::sync));
```

The stream is an attribute of my class, hence the `unique_ptr`. I'm then executing async operations on this stream, for instance:

```cpp
cuda::memory::async::copy(
    dest.data_ptr(),
    src.data_ptr(),
    count,
    *m_client_stream_sync.get() // attribute of my class, initialized in the constructor above and used many times during the execution
);
```

However, calls to `async::copy` or `::copy` are always failing in my distributed setting, triggering the following error:

```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Scheduling a memory copy on stream 0x076da420: context is destroyed
```

The confusing thing for me is that my program is working just fine when using one process, i.e., `mpiexec -np 1 -hosts ip:1 ...` doesn't trigger any error.

NB: I tried to initialize my stream using the following to remove uncertainties about the life cycle of the unique_ptr, but I get the same `context is destroyed` error.
```cpp
std::generate_n(
    std::back_inserter(streams), 1, [&device]() {
        return device.create_stream(cuda::stream::sync);
    }
);
```

What could cause the context to be destroyed in my MPI distributed setting? Thanks!

**Comment by eyalroz** [comment]
> The stream is an attribute of my class, hence the unique_ptr

I'm not sure I understand; a `stream_t` is just a wrapper, there's no problem with making as many (non-owning) copies of it as you like. And the owning copy will release the actual CUDA stream upon destruction. So a unique_ptr is redundant for it, I believe.

**Comment by thomas-bouvier** [comment]
Sorry, I was not clear enough explaining my issue. I will put it differently. In my application, replacing the stream creation done with the official CUDA API:

```cpp
// CUDA API
int num_devices = 0;
cudaGetDeviceCount(&num_devices);
cudaSetDevice(m_rank % num_devices);

cudaStreamCreate(&m_streams[0]);
cudaStreamCreate(&m_streams[1]);
cudaStreamCreate(&m_streams[2]);
```

With these wrappers:

```cpp
auto device = cuda::device::get(m_rank % cuda::device::count());
device.make_current();

std::generate_n(
    std::back_inserter(m_streams), 1, [&device]() {
        return device.create_stream(cuda::stream::sync);
    }
);
```

And replacing async transfers as follows, from:

```cpp
CHECK_CUDA_ERROR(cudaMemcpyAsync(
    (char *) batch.aug_samples.data_ptr(),
    batch.samples.data_ptr(),
    batch.get_size() * num_bytes_per_representative,
    cudaMemcpyDefault,
    m_streams[0]
));
```

To:

```cpp
cuda::memory::async::copy(
    (char *) batch.aug_samples.data_ptr(),
    batch.samples.data_ptr(),
    batch.get_size() * num_bytes_per_representative,
    m_streams[0]
);
```

Yields to the following error (slightly different than in the first post, but the underlying issue is probably similar):

```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Scheduling a memory copy on stream 0x0: invalid device context
 *** Process received signal ***
 Signal: Aborted (6)
 Signal code:  (-6)
```

To clarify, I was mentioning unique_ptrs in my first post, as the error message was related to 'destroyed contexts', which could have been related to object lifetime. With this new test (drop-in replacement of usual CUDA calls with this new API), there is no pointer involved anymore. The error changed though `invalid device context`. I hope this better illustrates my issue.

This error is occuring when the application is run on more than 1 MPI process (each process being attached to a different CUDA device). I'm not doing IPC.

**Comment by eyalroz** [comment]
> the official CUDA API

That's one of the official APIs - the "Runtime API", and the bad one. I mean, it's perhaps simpler for newbies, but it interacts poorly with everything due to a bunch of global state. You see, the Runtime API uses a singular implicit device context, which must be kept alive through a refcounting mechanism, and possibly also kept as the current context. As long as you only use the Runtime API, this works. But once you start using anything else, you run the risk of getting into trouble.

If you can produce and send me, or post here, a program with which this issue is triggered, I can look into the details. Otherwise - I don't generally support mixed use of my wrappers and the runtime API. Mixed use with the _driver_ API I would support, since there you have control of what you're doing.
