### ISSUE TITLE
std::is_trivially_copy_constructible requirement for kernel parameters still too strong

### ISSUE THREAD

**Issue by pauleonix** [eyalroz/cuda-api-wrappers#551]
Even the most basic "fancy iterator" from Thrust ~~`thrust::constant_iterator`~~ `thrust::counting_iterator` doesn't fulfill the requirement making algorithms written using cuda-api-wrappers for launching kernels less flexible.

<details> 
  <summary> <strike> <code>constant_iterator</code> constructor </strike> </summary>
```cuda
    __host__ __device__
    constant_iterator(constant_iterator const &rhs)
      : super_t(rhs.base()), m_value(rhs.m_value) {}
```
</details>

```cuda
    __host__ __device__
    counting_iterator(counting_iterator const &rhs):super_t(rhs.base()){}
```

See ~~[Compiler Explorer](https://cuda.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:cuda,selection:(endColumn:2,endLineNumber:7,positionColumn:2,positionLineNumber:7,selectionStartColumn:1,selectionStartLineNumber:7,startColumn:1,startLineNumber:7),source:'%23include+%3Ctype_traits%3E%0A%0A%23include+%3Cthrust/iterator/constant_iterator.h%3E%0A%0Avoid+foo(void)+%7B%0A++++static_assert(std::is_trivially_copy_constructible_v%3Cthrust::constant_iterator%3Cint%3E%3E)%3B%0A%7D'),l:'5',n:'0',o:'CUDA+C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nvcc122u1,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:cuda,libs:!(),options:'-std%3Dc%2B%2B17',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+NVCC+12.2.1+(Editor+%231)',t:'0'),(h:output,i:(compilerName:'NVCC+12.2.1',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+NVCC+12.2.1+(Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)~~ [Compiler Explorer](https://cuda.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:cuda,selection:(endColumn:35,endLineNumber:3,positionColumn:35,positionLineNumber:3,selectionStartColumn:35,selectionStartLineNumber:3,startColumn:35,startLineNumber:3),source:'%23include+%3Ctype_traits%3E%0A%0A%23include+%3Cthrust/iterator/counting_iterator.h%3E%0A%0Avoid+foo(void)+%7B%0A++++static_assert(std::is_trivially_copy_constructible_v%3C%0A++++thrust::counting_iterator%3Cint%3E%0A++++%3E)%3B%0A%7D'),l:'5',n:'0',o:'CUDA+C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nvcc122u1,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:cuda,libs:!(),options:'-std%3Dc%2B%2B17',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+NVCC+12.2.1+(Editor+%231)',t:'0'),(h:output,i:(compilerName:'NVCC+12.2.1',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+NVCC+12.2.1+(Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:1,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by eyalroz** [comment]
To justify your suggestion, please disprove my logic for choosing this trait:

An argument of a kernel does not get "copy-constructed" in GPU global memory; it is copied as raw bytes. Thus, if it cannot be copy-constructed by trivial copying - it cannot be assumed to be a valid constructed object of the relevant type.

**Comment by pauleonix** [comment]
Well, in theory `constant_iterator<T>` is just a `T` with some iterator-specific accessor functions and therefore trivially copyable. But `std::is_trivially_copy_constructible` still wont agree to that in practice.

In practice I can't update my research group's codebases using cuda-api-wrappers 0.4.x to use >=0.5. And in practice I expect a C++ library for CUDA programming to be composable with Thrust iterators. I don't expect the Thrust team to change their working API for this `static_assert`. But if you disagree with that expectation, I can try.

Maybe a preprocessor switch to turn of that `static_assert` is the right middle ground?

**Comment by eyalroz** [comment]
I can't go on what a type should be "in theory". If you write:
```
struct foo {
    int x, y;
    foo(const foo& f) : x(f.x), y(f.y) { }
}
```
I can't accept your struct, since the compiler doesn't "know" that this is equivalent to trivial copy construction. And that copy ctor could, in principle, say, flip x and y if we're on the device side and not flip them on the host side.

...

but - now that you mention it, I did a bit of DDG'ing, and I'm wondering whether `std::is_trivially_copyable` is the trait I need. Does the `const_iterator<T>` you're interested in satisfy that?

**Comment by pauleonix** [comment]
I just chose `thrust::const_iterator`, because I thought it were the most basic (now that I read/understood more of the source, [`thrust::counting_iterator`](https://github.com/NVIDIA/cccl/blob/main/thrust/thrust/iterator/counting_iterator.h) is the most basic one made up just of a `T` in terms of state while `constant_iterator` needs an additional counter to make distances/ranges work). In fact all Thrust fancy iterators I tested  seem to be neither trivially copyable nor trivially copy-constructible. It is a bit hard to decipher the source due to multiple layers of CRTP (`counting_iterator` -> `counting_iterator_base` -> `iterator_adaptor` -> `itrator_adaptor_base` -> `iterator_facade` I think), so I'm not sure why that is the case. There is even a

```c++
#if THRUST_CPP_DIALECT >= 2011
    counting_iterator & operator=(const counting_iterator &) = default;
#endif
```

What I know is that all these iterator types are supposed to be safe in regards to passing them as kernel parameters.

**Comment by eyalroz** [comment]
> What I know is that all these iterator types are supposed to be safe in regards to passing them as kernel parameters.

Let's say I'm willing to accept it on faith that these types are safe for passing. So, shall I hard-code somehow for all the thrust iterator types you tell me about? That doesn't sound right (if it's at all doable). But if I don't hard-code, and instead just remove the restriction - who's to say users won't pass a `struct foo` from my example? 

"I know it should be safe" is not a criterion I can work with... how about you open a bug report against thrust (or the [unified CCCL](https://github.com/NVIDIA/cccl/)) about this, and post a link here? I'm willing to have a discussion about this with the developers there. Maybe there's an option I'm failing to consider.

**Comment by pauleonix** [comment]
https://github.com/NVIDIA/cccl/discussions/562

**Comment by eyalroz** [comment]
@pauleonix : Do you think there'll be any traction from the NVIDIA side?

**Comment by eyalroz** [comment]
I don't see what's the big deal in just fixing the iterators on their side.

**Comment by pauleonix** [comment]
What I know is that they are [working on ranges](https://github.com/NVIDIA/cccl/discussions/1333#discussioncomment-8348738), so I expect some kind of `iota_view` etc. in the not-too-far future. If this will fix this particular issue or still use the existing iterators or a similar mechanism under the hood, I don't know.

**Comment by eyalroz** [comment]
If they would just drop the ridiculous pretense to maintain their own individual C++ standard library implementation, I'm sure they would have plenty of time to interoperability of their more relevant libraries.

**Comment by eyalroz** [comment]
So, we can close this. But - note I am considering strengthening the requirements further: #642 .
