### ISSUE TITLE
Add port to VCPKG

### ISSUE THREAD

**Issue by eclipse0922** [eyalroz/cuda-api-wrappers#554]
For your information.

I wrote a vcpkg port and created a PR.
I just added some more modfication to @eladm-ultrawis 's original PR
It's been tested in CI and appears to be working fine.

I'd appreciate it if you could take a look at it when you get a chance.

https://github.com/microsoft/vcpkg/pull/35376

**Comment by eyalroz** [comment]
Thank you, @eclipse0922 , for taking the time to add the library to the vcpkg repositories :-)

I'm always glad at the prospect of expanding the exposure and user base, and this should help. I've tried once before to add the wrapper library into conan, but got stuck trying to figure out how to prepare a 'conan recipe' for it

**Comment by eclipse0922** [comment]
merged!

**Comment by eyalroz** [comment]
@eclipse0922 : FYI:
https://github.com/microsoft/vcpkg/pull/38506#issuecomment-2087345157

**Comment by eyalroz** [comment]
@eclipse0922 : As I update the version on vcpkg - should I always just provide the latest version, or should I maintain the "last N"?

**Comment by eclipse0922** [comment]
@eyalroz 
When updating the version in vcpkg, you typically just need to provide the latest version. Since vcpkg accesses the source code through the git history, older versions can still be accessed if needed. There's usually no need to maintain the "last N" versions unless there's a specific reason to do so.
