### ISSUE TITLE
Providing a cuda-api-wrappersConfig.cmake?

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#58]
Instead of providing a find module a talk by Daniel Pfeiffer:

https://www.youtube.com/watch?v=bsXLMQ6WgIk

summarised in:

https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/

suggest to provide rather a `cmake` config file, if the package also uses `cmake` as a build system.
It can be also very handy if the package registers within the `cmake` user package registry at `~/.cmake/packages`.

What do you think?

**Comment by eyalroz** [comment]
Thank you for the links. I hope to find the time to go over that in the near future, but this will not happen immediately. If you'd like to write something like that I'll happily review a pull request.

**Comment by eyalroz** [comment]
So, I now provide a `.cmake` file like you suggested. However:

1. It's on a separate branch, not the main one, which I've decided to be less wildly experimental with.
2. I haven't tried using it
3. I haven't been able to "link" the installation of header files to the export set

Help with this would be appreciated.

**Comment by codecircuit** [comment]
See #60

**Comment by codecircuit** [comment]
I think this is done with #102
