### ISSUE TITLE
std::atomic-like wrapper for atomic functions

### ISSUE THREAD

**Issue by lahwaacz** [eyalroz/cuda-api-wrappers#64]
In C++11, the canonical interface for atomic operations is [std::atomic](https://en.cppreference.com/w/cpp/atomic/atomic). Have you thought about wrapping the CUDA functions in a similar way?

**Comment by eyalroz** [comment]
I have such wrappers in my own code, but - that's not part of the CUDA Runtime API, and this repository is only about that.

I've thought about publishing a library of low-level primitives, definitions and utilities; and I might do that at some point.

**Comment by eyalroz** [comment]
@lahwaacz : please email me about that in more detail, as this page is not the appropriate venue for us to discuss this subject.
