### ISSUE TITLE
unique_span deleted copy constructors should ignore source deleter type

### ISSUE THREAD

**Issue by kdkavanagh** [eyalroz/cuda-api-wrappers#662]
I initially didnt catch that `cuda::memory::host::make_unique_span` and `cuda::memory::device::make_unique_span` do not both return the same type due to the different deleter required for the device span.  I missed it because of the identically-named but differently-defined `using unique_span = ...` aliases for device/host.

My issue arose when I assigned the results of both those calls to an object of type `cuda::unique_span<T>`.  
Even though copy-constructors are explicitly deleted, `unique_span` has a ctor which accepts a `std::span` as a copy:
```
explicit unique_span(span_type span) noexcept : span_type{span} { }
```

Since a `cuda::memory::device::unique_span` is not technically the same type as `cuda::unique_span`, the deleted copy constructor is ignored, and since the unique_span types extend `std::span`, that unique_span(span_type span) constructor is called, ending up with two `unique_spans` "owning" the data 

A fix for this would probably add an explicit deleted constructor for _any_ `unique_span` type rather than just a deleted ctor for the _same_ `unique_span` type:

```
template<typename OtherT, typename OtherDeleter>
explicit unique_span(const unique_span<OtherT, OtherDeleter>&) = delete;
```

**Comment by eyalroz** [comment]
A few thoughts...

* I had thought that making the construction from `span<T>` explicit was enough, but I guess that's not the case...
* Perhaps I should also mark move constructions as deleted.
* Why did you mark the deleted constructors with `explicit`? I want to make it easier to hit the deletion, not harder...

**Comment by kdkavanagh** [comment]
Move constructors definitely needed + are perfectly appropriate (i.e same as `std::unique_ptr`)

re: explicit, just a bad copy-paste into github.  Definitely not needed
