### ISSUE TITLE
Use std::chrono api for cudaEvent

### ISSUE THREAD

**Issue by OpportunityLiu** [eyalroz/cuda-api-wrappers#68]
The return type of `cuda::event::milliseconds_elapsed_between` can be `std::chrono::duration<float, std::milli>` and then it can be renamed to `elapsed_between`.

Types like `std::chrono::nanoseconds` can also be considered but a conversion from `float` to `long long` will be needed.

**Comment by eyalroz** [comment]
So, you're proposing two things: 
1. Using an `std::chrono`-based return type.
2. Naming that type `elapsed_between`.
With respect, I'm ignoring the second suggestion for now. But the main suggestion is very interesting.

Pros (for adopting it):

1. Using "dimensioned" types for "dimensioned" values is better.
2. Would move information about the type from the function name to the type name.
3. Slightly easier to work with using standard-library facilities.

Cons (for adopting it):

1. Creates a dependence on `<chrono>`, which drags in a lot of code (if you weren't using `<chrono>` already).
2. A duration with numeric type float is a bit esoteric, so people will often just want to unpack it into the float value

Can you discuss how you see these considerations?

I'd also like to ask @codecircuit (the most active user w.r.t. QA) what his opinion is. (if he's getting notified at least).

**Comment by OpportunityLiu** [comment]
I means rename the function to `elapsed_between` since the unit can be implied from the return type.

And the function `cuda::event::milliseconds_elapsed_between` can be remained.

**Comment by eyalroz** [comment]
@OpportunityLiu : You know what? It actually makes sense to have that dependency, since "events" are time-related anyway. Ok, done: Please check out the development branch and have a look.

**Comment by OpportunityLiu** [comment]
IMO, `milliseconds_` should not be a part of the function name, since it can be implied from the type of the return value.

`milliseconds_elapsed_between` can be remaind to return a `float` value.

**Comment by OpportunityLiu** [comment]
Found `* Renamed `milliseconds_elapsed_between()` -> `time_elapsed_between()`, and made it return a duration, so we don't need the function name to qualify the return type.` in commit message, but not in the code.

**Comment by eyalroz** [comment]
@OpportunityLiu : Whoops, right you are.
