### ISSUE TITLE
Avoid dependency on pthread.h which is unavailable on Windows

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#70]
Thanks for an awesome library!

On windows, the `<pthread>` header is not available. Is the expectation on windows to install a "windows compatible" version of posix threads? Or would the use of `std::thread` be possible?

**Comment by eyalroz** [comment]
Sorry for the mess. I now use exactly what nvToolkitEx uses, which is `uint32_t`'s for thread IDs. This is ugly (I wouldn't do that) - but the ugliness is already in there, so I'm not really making anything much uglier.

Please open a second bug about allowing such calls with `std::thread` arguments.

**Comment by DeveloperPaul123** [comment]
@eyalroz I actually looked into it and getting a `uint32_t` from `std::thread::id` is non-trivial. I'll open a new issue if needed. Thanks for the quick fix.

**Comment by DeveloperPaul123** [comment]
I tried out your changes and `pthread_self()` is still used in `profiling.cpp`. Is you statement about about opening another issue about allowing such calls with `std::thread` more about replacing the use of `pthread` with `std::thread`?

**Comment by eyalroz** [comment]
Oh, yes, sorry. Hope to correct this tonight.

**Comment by DeveloperPaul123** [comment]
There are also some further issues with compiling on windows. The last thing I had to correct was the use of the `and`  keyword which doesn't exist in MSVC by default (you have to include a specific header).

Additionally most of the examples do not compile out of the box on Windows. Would you like me to file a PR to correct these two items?

**Comment by eyalroz** [comment]
I'd like you open separate issues for them, then we'll see.
