### ISSUE TITLE
Undefined Keywords [Windows]

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#73]
On windows, the `and` keyword (among others) is not defined by default. I would suggest opting for more "traditional" logical operators like `&&` and `||`, or on windows you can include the header `iso646.h` to get the definitions of the logical operators as you have them. 

The issue is in [types.hpp](https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/types.hpp#L116).

**Comment by eyalroz** [comment]
So, please try this (e.g. by checking out the development branch) and let me know.

**Comment by DeveloperPaul123** [comment]
I'm aware that they are C++ keywords. I labeled this as a Windows issue since this is specific to Visual Studio, which traditionally (and up until recently) has been a Windows only IDE. 

The inclusion of `<ciso646>` works as expected. Another option is to pass the `/permissive-` flag to the MSVC compiler instead of including this header. I've tried both and they both work. See [this](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/) for more info.

**Comment by eyalroz** [comment]
I'd rather include an extra header than tell a compiler to be permissive...

**Comment by DeveloperPaul123** [comment]
That seems reasonable to me.

**Comment by DeveloperPaul123** [comment]
All good now 👍
