### ISSUE TITLE
Non-Portable Path to NVTX Headers [Windows]

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#74]
On Windows with CUDA 10.0 installed, the paths to the NVTX headers that are used in `profiling.cpp` need to be prepended with `nvtx3` so that the full include path is `nvtx3/nvToolsExt.h` and `nvtx3/nvToolsExtCudaRt.h`.  Not sure how to make a "portable" solution here other than just hacking together the include paths based on the OS. 

One would think that the include paths should be the same if everything is being found correctly via CMake.

**Comment by eyalroz** [comment]
No work on CUDA 10 supprot has begun yet.

**Comment by DeveloperPaul123** [comment]
Ok, I'll see if this happens to be an issue for me with other CUDA versions.

**Comment by eyalroz** [comment]
I will definitely get to this - just not within the next few days. If you want to propose a quick-fix PR I'll consider it favorably.

**Comment by DeveloperPaul123** [comment]
This may be a dumb question, but since you're not using `find_package` in this project, I don't see any obvious way to select what version of CUDA to use when building your lib. Do you know a way to do this?

**Comment by eyalroz** [comment]
First, to answer the initial question - I've tested with CUDA 10, and the include files are still right there on Linux. What do you feel about adding the nvtx3 subdirectory to the include path on Windows?

**Comment by eyalroz** [comment]
How about this workaround?

```
# A best-effort attempt to address an include location issue under Windows.
# This will fail if for some reason there are _multiple_ include directories.
list(LENGTH CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES NUM_CUDA_INCLUDE_DIRS)
if(${NUM_CUDA_INCLUDE_DIRS} EQUAL 1 AND EXISTS "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}/nvtx3" AND IS_DIRECTORY "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}/nvtx3")
    include_directories( "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}/nvtx3" )
endif()
```

**Comment by DeveloperPaul123** [comment]
I think that could work actually, and we (me or you) could extend it to work even if the number of include directories is > 1. 

Also, for clarity, here's what the include directory looks like in the install directory of the CUDA 10.0 toolkit on my windows machine:

![image](https://user-images.githubusercontent.com/6591180/48203300-1f239e80-e335-11e8-88f5-46bacdcd5b67.png)

**Comment by eyalroz** [comment]
This should be resolved after PR #92 - @DeveloperPaul123 , please ensure that is indeed the case.

**Comment by DeveloperPaul123** [comment]
@eyalroz I should be able to test this out this week.

**Comment by DeveloperPaul123** [comment]
@eyalroz 

#92 did fix the NVTX path issue, but none of the examples compile successfully for me. I'll look through the issues to see if that is logged already. Haven't had time to do that yet...

**Comment by eyalroz** [comment]
Sure - one thing at a time.

**Comment by eyalroz** [comment]
@DeveloperPaul123 : Could you check the NVTX path situation with newer CUDA 11.x versions and Windows 10?

**Comment by DeveloperPaul123** [comment]
@eyalroz I tried things out with (Winows 10):
 - Visual Studio 2019 (C++17 compiler)
 - CMake `3.21.2`
 - CUDA `11.5`

Looks like the NVTX path issue is fine, your solution still works with the `#ifdef` clause. The library builds fine for me out of the box with this setup, but the examples still fail to compile.

**Comment by eyalroz** [comment]
@DeveloperPaul123 : Would you mind filing an issue / several issues for the compilation errors you see with the examples?

Also, note I'm working on reducing the amount of gratuitous warning messages you're getting, so if you can find the time for this, please use the development branch and not before tomorrow.

**Comment by DeveloperPaul123** [comment]
@eyalroz Sure I think I can do that. Would you like separate issues for the warnings versus compilation errors? And do you mean to not file the issues before tomorrow?

**Comment by eyalroz** [comment]
Separate, please.

And - tomorrow is now :-) ... I've made some commits which help with warnings and errors; but also, unfortunately, commits which may break the build on windows, like trying to better formalize the dependency on NVTX.

**Comment by DeveloperPaul123** [comment]
No problem, I can hold off if you'd like to try and tackle the issues first?

**Comment by eyalroz** [comment]
Actually, please don't... if you encounter build problems, just make the dependence on nvToolkitExt PRIVATE rather than public. Otherwise it should be done.
