### ISSUE TITLE
Use Static Cast to Convert to/from `nvtxRangeId_t` [Windows]

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#75]
In `profiling.cpp`, when compiling using Visual Studio 2017, an error is thrown [here](https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/profiling.cpp#L55) and [here](https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/profiling.cpp#L60). Visual studio doesn't seem to like the use of `reinterpret_cast` here. A easy solution is to replace it with `static_cast`.

**Comment by eyalroz** [comment]
`static_cast` seems too risky... I'll just ensure they're identical rather than just the same size.

**Comment by eyalroz** [comment]
Note again that the fix is on the development branch.

**Comment by eyalroz** [comment]
I really need to get me a Windows platform to test on, so as to avoid such gaffes. Sorry.

**Comment by DeveloperPaul123** [comment]
All good now 👍
