### ISSUE TITLE
Compilation Fails if `BUILD_SHARED_LIBS` is Turned On [Windows]

### ISSUE THREAD

**Issue by DeveloperPaul123** [eyalroz/cuda-api-wrappers#76]
Currently, you will get unresolved symbol errors if you turn `BUILD_SHARED_LIBS` on in CMake and try to compile the library.

**Comment by eyalroz** [comment]
I haven't really thought about people forcing my library to build as shared rather than static. Well, I hope a bit of simple `CMakeLists.txt` can ameliorate this.

**Comment by DeveloperPaul123** [comment]
febc33a did not fix the issue. You need to use an export macro to indicate that the library needs to be exported to a dynamic library (`.dll` on windows). Use can use [`generate_export_header()`](https://cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html) in CMake to auto generate this export header for you.

I can also do this as well if you prefer to just have a PR to review.

**Comment by eyalroz** [comment]
Oh, I'd definitely like a PR - especially for the case of a platform I can't test on right now...

**Comment by eyalroz** [comment]
@DeveloperPaul123 : Ping?

**Comment by DeveloperPaul123** [comment]
I should be able to file a PR this week.

**Comment by eyalroz** [comment]
Great :-) 

Remember I have a [`development` branch](https://github.com/eyalroz/cuda-api-wrappers/tree/development) - if you can PR against it, that would be great. But a PR against master is fine too.

**Comment by DeveloperPaul123** [comment]
I'll definitely PR against the development branch; I think that's much cleaner and in general I leave the master branch for releases.

**Comment by DeveloperPaul123** [comment]
This has been solved with #80

**Comment by eyalroz** [comment]
Well, only on the development branch; it (should) auto-close when I land development on master again...

**Comment by DeveloperPaul123** [comment]
My bad, got a little over zealous
