### ISSUE TITLE
Arrays of Length Zero

### ISSUE THREAD

**Issue by Gawaboumga** [eyalroz/cuda-api-wrappers#81]
Hello, it's me [again](https://github.com/eyalroz/cuda-api-wrappers/pull/43),

I wanted to update my dependence on this repository. And I encountered two small problems with Visual Studio C++ 17:
- For the first, it was enough to apply the solution proposed here: https://github.com/eyalroz/cuda-api-wrappers/issues/73 no problems.
- But, for the second one, it's related to the line: https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/kernel_launch.cuh#L142
Indeed, the "Arrays of Length Zero" are a compiler extension. 

So, I tried a workaround to solve this issue:
```
template <size_t n>
struct ParametersToArguments
{
	template <typename... KernelParameters>
	void** operator()(KernelParameters... parameters) const
	{
		// fill the argument array with our parameters. Yes, the use
		// of the two terms is confusing here && depends on how you
		// look at things.
		detail::collect_argument_addresses(argument_ptrs, std::forward<KernelParameters>(parameters)...);
		return argument_ptrs;
	}

	void* argument_ptrs[n];
};

template <>
struct ParametersToArguments<0>
{
	template <typename... KernelParameters>
	void** operator()(KernelParameters...) const
	{
		return nullptr;
	}
};

...

		ParametersToArguments<sizeof...(KernelParameters)> tmp;
		void** argument_ptrs = tmp(parameters...);

		auto status = cudaLaunchCooperativeKernel( // bla bla bla
```

What do you think of that? It's a bit ugly :/
Thank you for this great library !

**Comment by eyalroz** [comment]
It's not fixed on the main branch yet.
