### ISSUE TITLE
No default parameter expansion on Command Substitution

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#84]
In `get_cuda_sm.sh`: `nvcc_default_path=$(which nvcc:-"/usr/local/cuda/bin/nvcc")`

I think you can not use default parameter expansion in a bash command substitution. I rather suggest to check if `nvcc` is in `PATH` first. If it is not you can still check the default path.

This might be helpful:

```bash
which nvcc &> /dev/null && { nvcc_path=$(which nvcc); }
#check if nvcc_path is empty
```

**Comment by eyalroz** [comment]
@codecircuit : I now do this:
```
nvcc_fallback_in_path=$(which nvcc)
nvcc_fallback=${nvcc_fallback_in_path:-"/usr/local/cuda/bin/nvcc"}
unset nvcc_fallback_in_path
```
which should be ok. By the way - a missing binary doesn't trigger an error message. So I don't think I need the &> `/dev/null`
