### ISSUE TITLE
Compilation issues Windows / CUDA 10.0

### ISSUE THREAD

**Issue by jvschroeder** [eyalroz/cuda-api-wrappers#96]
I encountered the following issues trying to compile the examples on Windows using CUDA 10.0

* Using the '-rdc' flag leads to linker errors for the execution_control example. Skipping it (cf. jvschroeder@f94b66f115332efd7209f32c05c2b00a2b6e2733) fixes that
* If the cuda::grid_dimensions_t and cuda::grid_block_dimensions_t are not explicitly created (in the vectorAdd example) the compiler reports a type-narrowing error (cf. jvschroeder@79cf1816e50a164fb5ccb0b78c36c0ba40eea1d1)

> ./cuda-api-wrappers/examples/modified_cuda_samples/vectorAdd/vectorAdd.cu(60): error C23
> 97: conversion from 'int' to 'cuda::grid_dimensions_t' requires a narrowing conversion [...]
> ./cuda-api-wrappers/examples/modified_cuda_samples/vectorAdd/vectorAdd.cu(60): error C23
> 97: conversion from 'int' to 'cuda::grid_block_dimensions_t' requires a narrowing conversion [...]

* Without some static_casts in the device_management example the compiler reports type conversion errors (cf. jvschroeder@6565ca19befe9bc275bdc1f8301c702ff19ec2fa)

> .\cuda-api-wrappers\examples\by_runtime_api_module\device_management.cpp(65): error C266
> 4: 'cuda::device_t<false>::attribute_value_t cuda::device_t<false>::get_attribute(cuda::device_t<false>::attribute_t) c
> onst': cannot convert argument 1 from 'cudaDeviceAttr' to 'cuda::device_t<false>::attribute_t'

**Comment by eyalroz** [comment]
Are you still experiencing all of these issues?

**Comment by jvschroeder** [comment]
Haven't given it a try recently, but I can try tomorrow if you're interested?

**Comment by eyalroz** [comment]
Sure, no pressure.

**Comment by eyalroz** [comment]
Have you tried reproducing this issue?

**Comment by jvschroeder** [comment]
Hi, sorry I was a bit busier than expected and forgot. 

The master branch still has the same issues:

>  Error	C2664	'cuda::device_t<false>::attribute_value_t cuda::device_t<false>::get_attribute(cuda::device_t<false>::attribute_t) const': cannot convert argument 1 from 'cudaDeviceAttr' to  'cuda::device_t<false>::attribute_t'	device_management	E:\cuda-api-wrappers\examples\by_runtime_api_module\device_management.cpp	65	
> 
> Error	C3536	'max_registers_per_block': cannot be used before it is initialized	device_management	E:\cuda-api-wrappers\examples\by_runtime_api_module\device_management.cpp	68	
> 
> Error	C2397	conversion from 'int' to 'cuda::grid_dimensions_t' requires a narrowing conversion	vectorAdd	E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd\vectorAdd.cu	60	
> 
> Error	C2397	conversion from 'int' to 'cuda::grid_block_dimensions_t' requires a narrowing conversion	vectorAdd	E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd\vectorAdd.cu	60	
> 

And development doesn't seem to compile at all:
![image](https://user-images.githubusercontent.com/25535055/73018408-debd1d00-3e21-11ea-9ac0-134a246b87b8.png)

**Comment by eyalroz** [comment]
To be honest, those messages don't make sense... take the first one for example: `'cuda::device_t::attribute_t` is defined to be `cuda::device::atribute_t`; and the latter is defined in `types.hpp` to be `enum cudaDeviceAttr`...

I need to see a self-contained example of this failing. That is:

1. A single (short) source file, `file.cu` or `file.cpp`
2. A command to run (e.g. `cl.exe /something /something_else file.cpp` or `nvcc.exe -something -something_else file.cu`)
3. A list of all of your environment variables 

Specifically - show this to me without the IDE.

**Comment by jvschroeder** [comment]
vectorAdd.cu and device_management.cpp yield the same result when directly calling nvcc:

> E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd>nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
> Cuda compilation tools, release 10.0, V10.0.130
> 
> E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd>cl
> Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> usage: cl [ option... ] filename... [ /link linkoption... ]
> 
> E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd>nvcc vectorAdd.cu -I ../../../src
> vectorAdd.cu
> vectorAdd.cu(60): error C2397: conversion from 'int' to 'cuda::grid_dimensions_t' requires a narrowing conversion
> vectorAdd.cu(60): error C2397: conversion from 'int' to 'cuda::grid_block_dimensions_t' requires a narrowing conversion
> 
> E:\cuda-api-wrappers\examples\modified_cuda_samples\vectorAdd>cd ../../by_runtime_api_module/
> 
> E:\cuda-api-wrappers\examples\by_runtime_api_module>nvcc device_management.cpp -I ../../src
> device_management.cpp
> device_management.cpp(65): error C2664: 'cuda::device_t<false>::attribute_value_t cuda::device_t<false>::get_attribute(cuda::device_t<false>::attribute_t) const': cannot convert argument 1 from 'cudaDeviceAttr' to 'cuda::device_t<false>::attribute_t'
> device_management.cpp(65): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
> device_management.cpp(68): error C3536: 'max_registers_per_block': cannot be used before it is initialized

Unfortunately I don't have any time to distill these files into smaller examples.

**Comment by eyalroz** [comment]
Ah, ok, if it's my own examples then you don't need to synthesize anything.

Ah... I see now about the conversion business. That's a weird error. I'll try and look into it.

**Comment by eyalroz** [comment]
Please recheck again with the tip of the development branch.

**Comment by eyalroz** [comment]
@jvschroeder : Please reopen if you still experience this issue.
